// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/lf/three_schedules/three_schedules.lf
#include "ctarget.h"
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class ThreeSchedules
#line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
typedef struct {
#line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    trigger_t* trigger;
#line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    bool is_present;
#line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    bool has_value;
#line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    token_t* token;
#line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
} threeschedules_act_t;
typedef struct {
    int bank_index;
    #line 7 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    int s;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    threeschedules_act_t __act;
    #line 10 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    reaction_t ___reaction_0;
    #line 14 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    reaction_t ___reaction_1;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    trigger_t ___act;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    reaction_t* ___act_reactions[1];
} threeschedules_self_t;
void threeschedulesreaction_function_0(void* instance_args) {
    threeschedules_self_t* self = (threeschedules_self_t*)instance_args;
    threeschedules_act_t* act = &self->__act;
    #line 11 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    schedule(act, MSEC(100));
        
}
void threeschedulesreaction_function_1(void* instance_args) {
    threeschedules_self_t* self = (threeschedules_self_t*)instance_args;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    // Expose the action struct as a local variable whose name matches the action name.
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    threeschedules_act_t* act = &self->__act;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    // Set the fields of the action struct to match the current trigger.
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    act->is_present = self->___act.is_present;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    act->has_value = ((self->___act.token) != NULL && (self->___act.token)->value != NULL);
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    act->token = (self->___act.token);
    #line 15 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    if (self->s < 3) {
        self->s += 1;
        schedule(act, MSEC(100));
    }
        
}
threeschedules_self_t* new_ThreeSchedules() {
    threeschedules_self_t* self = (threeschedules_self_t*)calloc(1, sizeof(threeschedules_self_t));
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->__act.trigger = &self->___act;
    #line 10 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_0.function = threeschedulesreaction_function_0;
    #line 10 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_0.self = self;
    #line 10 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 10 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 14 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_1.function = threeschedulesreaction_function_1;
    #line 14 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_1.self = self;
    #line 14 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_1.deadline_violation_handler = NULL;
    #line 14 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___reaction_1.tardy_handler = NULL;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___act.last = NULL;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___act_reactions[0] = &self->___reaction_1;
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___act.reactions = &self->___act_reactions[0];
    #line 8 "file:/lf-flexpret-scripts/lf/three_schedules/three_schedules.lf"
    self->___act.number_of_reactions = 1;
    self->___act.is_physical = false;
    self->___act.element_size = 0;
    return self;
}
void delete_ThreeSchedules(threeschedules_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    if (self->___reaction_1.output_produced != NULL) {
        free(self->___reaction_1.output_produced);
    }
    if (self->___reaction_1.triggers != NULL) {
        free(self->___reaction_1.triggers);
    }
    if (self->___reaction_1.triggered_sizes != NULL) {
        free(self->___reaction_1.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    for(int i = 0; i < self->___reaction_1.num_outputs; i++) {
        free(self->___reaction_1.triggers[i]);
    }
    free(self);
}
// =============== END reactor class ThreeSchedules

char* __default_argv[] = {"X", "-f", "true"};
void __set_default_command_line_options() {
    default_argc = 3;
    default_argv = __default_argv;
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Empty array of pointers to shutdown triggers.
trigger_t** __shutdown_triggers = NULL;
int __shutdown_triggers_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 1;
    __tokens_with_ref_count = (token_present_t*)malloc(1 * sizeof(token_present_t));
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance ThreeSchedules of class ThreeSchedules
    threeschedules_self_t* threeschedules_self = new_ThreeSchedules();
    //***** Start initializing ThreeSchedules
    __startup_reactions[0] = &threeschedules_self->___reaction_0;
    static int threeschedules_initial_s = 0;
    threeschedules_self->s = threeschedules_initial_s;
    threeschedules_self->___act.offset = 0;
    threeschedules_self->___act.period = -1;
    threeschedules_self->___act.token = __create_token(0);
    threeschedules_self->___act.is_present = false;
    __tokens_with_ref_count[0].token
            = &threeschedules_self->___act.token;
    __tokens_with_ref_count[0].is_present
            = &threeschedules_self->___act.is_present;
    __tokens_with_ref_count[0].reset_is_present = true;
    //***** End initializing ThreeSchedules
    // Populate arrays of trigger pointers.
    threeschedules_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    threeschedules_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (threeschedules_self->___reaction_0.num_outputs > 0) {
        threeschedules_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * threeschedules_self->___reaction_0.num_outputs);
        threeschedules_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * threeschedules_self->___reaction_0.num_outputs);
        threeschedules_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * threeschedules_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Total number of outputs produced by the reaction.
    threeschedules_self->___reaction_1.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (threeschedules_self->___reaction_1.num_outputs > 0) {
        threeschedules_self->___reaction_1.output_produced = (bool**)malloc(sizeof(bool*) * threeschedules_self->___reaction_1.num_outputs);
        threeschedules_self->___reaction_1.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * threeschedules_self->___reaction_1.num_outputs);
        threeschedules_self->___reaction_1.triggered_sizes = (int*)malloc(sizeof(int) * threeschedules_self->___reaction_1.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of ThreeSchedules does not depend on one maximal upstream reaction.
    threeschedules_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 1 of ThreeSchedules depends on one maximal upstream reaction.
    threeschedules_self->___reaction_1.last_enabling_reaction = &(threeschedules_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor ThreeSchedules.
    // END Connect inputs and outputs for reactor ThreeSchedules.
    // Add action ThreeSchedules.act to array of is_present fields.
    __is_present_fields[0] 
            = &threeschedules_self->__act.is_present;
    threeschedules_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    threeschedules_self->___reaction_0.index = 0x7fffffffffff0000LL;
    threeschedules_self->___reaction_1.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    threeschedules_self->___reaction_1.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_time_complete(instant_t time) {
}
instant_t next_event_time(instant_t time) {
    return time;
}
bool __wrapup() {
    __start_time_step();  // To free memory allocated for actions.
    for (int i = 0; i < __shutdown_triggers_size; i++) {
        __schedule(__shutdown_triggers[i], 0LL, NULL);
    }
    // Return true if there are shutdown actions.
    return (__shutdown_triggers_size > 0);
}
void __termination() {}
