#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/ActionIsPresent.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class ActionIsPresent
#line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
typedef struct {
#line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    trigger_t* trigger;
#line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    bool is_present;
#line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    bool has_value;
#line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    lf_token_t* token;
#line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
} actionispresent_a_t;
typedef struct {
    int bank_index;
    #line 3 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    interval_t offset;
    #line 3 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    interval_t period;
    #line 5 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    bool success;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    actionispresent_a_t __a;
    #line 6 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    reaction_t ___reaction_0;
    #line 19 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    reaction_t ___reaction_1;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
    trigger_t ___shutdown;
    reaction_t* ___shutdown_reactions[1];
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    trigger_t ___a;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    reaction_t* ___a_reactions[1];
} actionispresent_self_t;
void actionispresentreaction_function_0(void* instance_args) {
    actionispresent_self_t* self = (actionispresent_self_t*)instance_args;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    // Expose the action struct as a local variable whose name matches the action name.
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    actionispresent_a_t* a = &self->__a;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    // Set the fields of the action struct to match the current trigger.
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    a->is_present = self->___a.is_present;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    a->has_value = ((self->___a.token) != NULL && (self->___a.token)->value != NULL);
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    a->token = (self->___a.token);
    #line 7 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    if (!a->is_present) {
        if (self->offset == 0) {
            printf("Hello World!\n");
            self->success = true;
        } else {
            schedule(a, self->offset);
        }
    } else {
        printf("Hello World 2!\n");
        self->success = true;
    }
        
}
void actionispresentreaction_function_1(void* instance_args) {
    actionispresent_self_t* self = (actionispresent_self_t*)instance_args;
    #line 20 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    if (!self->success) {
        fprintf(stderr, "Failed to print 'Hello World'\n");
        exit(1);
    }
        
}
actionispresent_self_t* new_ActionIsPresent() {
    actionispresent_self_t* self = (actionispresent_self_t*)calloc(1, sizeof(actionispresent_self_t));
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->__a.trigger = &self->___a;
    #line 6 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_0.number = 0;
    #line 6 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_0.function = actionispresentreaction_function_0;
    #line 6 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_0.self = self;
    #line 6 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 6 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 19 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_1.number = 1;
    #line 19 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_1.function = actionispresentreaction_function_1;
    #line 19 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_1.self = self;
    #line 19 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_1.deadline_violation_handler = NULL;
    #line 19 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___reaction_1.tardy_handler = NULL;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    self->___shutdown_reactions[0] = &self->___reaction_1;
    self->___shutdown.last = NULL;
    self->___shutdown.reactions = &self->___shutdown_reactions[0];
    self->___shutdown.number_of_reactions = 1;
    self->___shutdown.is_timer = false;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___a.last = NULL;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___a_reactions[0] = &self->___reaction_0;
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___a.reactions = &self->___a_reactions[0];
    #line 4 "file:/lf-flexpret-scripts/tests/ActionIsPresent.lf"
    self->___a.number_of_reactions = 1;
    self->___a.is_physical = false;
    self->___a.element_size = 0;
    return self;
}
void delete_ActionIsPresent(actionispresent_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    if (self->___reaction_1.output_produced != NULL) {
        free(self->___reaction_1.output_produced);
    }
    if (self->___reaction_1.triggers != NULL) {
        free(self->___reaction_1.triggers);
    }
    if (self->___reaction_1.triggered_sizes != NULL) {
        free(self->___reaction_1.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    for(int i = 0; i < self->___reaction_1.num_outputs; i++) {
        free(self->___reaction_1.triggers[i]);
    }
    free(self);
}
// =============== END reactor class ActionIsPresent

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t* __shutdown_reactions[1];
int __shutdown_reactions_size = 1;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 1;
    __tokens_with_ref_count = (token_present_t*)malloc(1 * sizeof(token_present_t));
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance ActionIsPresent of class ActionIsPresent
    actionispresent_self_t* actionispresent_self = new_ActionIsPresent();
    //***** Start initializing ActionIsPresent
    actionispresent_self->offset = NSEC(1); 
    actionispresent_self->period = MSEC(500); 
    __startup_reactions[0] = &actionispresent_self->___reaction_0;
    __shutdown_reactions[0] = &actionispresent_self->___reaction_1;
    static bool actionispresent_initial_success = false;
    actionispresent_self->success = actionispresent_initial_success;
    actionispresent_self->___a.offset = 0;
    actionispresent_self->___a.period = -1;
    actionispresent_self->___a.token = __create_token(0);
    actionispresent_self->___a.is_present = false;
    __tokens_with_ref_count[0].token
            = &actionispresent_self->___a.token;
    __tokens_with_ref_count[0].is_present
            = &actionispresent_self->___a.is_present;
    __tokens_with_ref_count[0].reset_is_present = true;
    //***** End initializing ActionIsPresent
    // Populate arrays of trigger pointers.
    actionispresent_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    actionispresent_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (actionispresent_self->___reaction_0.num_outputs > 0) {
        actionispresent_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * actionispresent_self->___reaction_0.num_outputs);
        actionispresent_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * actionispresent_self->___reaction_0.num_outputs);
        actionispresent_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * actionispresent_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Total number of outputs produced by the reaction.
    actionispresent_self->___reaction_1.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (actionispresent_self->___reaction_1.num_outputs > 0) {
        actionispresent_self->___reaction_1.output_produced = (bool**)malloc(sizeof(bool*) * actionispresent_self->___reaction_1.num_outputs);
        actionispresent_self->___reaction_1.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * actionispresent_self->___reaction_1.num_outputs);
        actionispresent_self->___reaction_1.triggered_sizes = (int*)malloc(sizeof(int) * actionispresent_self->___reaction_1.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of ActionIsPresent does not depend on one maximal upstream reaction.
    actionispresent_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 1 of ActionIsPresent depends on one maximal upstream reaction.
    actionispresent_self->___reaction_1.last_enabling_reaction = &(actionispresent_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor ActionIsPresent.
    // END Connect inputs and outputs for reactor ActionIsPresent.
    // Add action ActionIsPresent.a to array of is_present fields.
    __is_present_fields[0] 
            = &actionispresent_self->__a.is_present;
    actionispresent_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    actionispresent_self->___reaction_0.index = 0x7fffffffffff0000LL;
    actionispresent_self->___reaction_1.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    actionispresent_self->___reaction_1.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
