#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/ArrayPrint.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Print
#line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
typedef struct {
#line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int* value;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    bool is_present;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int num_destinations;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    lf_token_t* token;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int length;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
} print_in_t;
typedef struct {
    int bank_index;
    #line 17 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int scale;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    print_in_t* __in;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    // width of -2 indicates that it is not a multiport.
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int __in__width;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    // Default input (in case it does not get connected)
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    print_in_t __default__in;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    reaction_t ___reaction_0;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    trigger_t ___in;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    reaction_t* ___in_reactions[1];
} print_self_t;
void printreaction_function_0(void* instance_args) {
    print_self_t* self = (print_self_t*)instance_args;
    print_in_t* in = self->__in;
    if (in->is_present) {
        in->length = in->token->length;
        in->value = (int*)in->token->value;
    } else {
        in->length = 0;
    }
    int in_width = self->__in__width;
    #line 20 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int count = 0;       // For testing.
    bool failed = false; // For testing.
    printf("Received: [");
    for (int i = 0; i < in->length; i++) {
        if (i > 0) printf(", ");
        printf("%d", in->value[i]);
        // For testing, check whether values match expectation.
        if (in->value[i] != self->scale * count) {
            failed = true;
        }
        count++;         // For testing.
    }
    printf("]\n");
    if (failed) {
        printf("ERROR: Value received by Print does not match expectation!\n");
        exit(1);
    }
        
}
print_self_t* new_Print() {
    print_self_t* self = (print_self_t*)calloc(1, sizeof(print_self_t));
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    // Set input by default to an always absent default input.
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->__in = &self->__default__in;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.number = 0;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.function = printreaction_function_0;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.self = self;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___in.last = NULL;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(int);
    return self;
}
void delete_Print(print_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Print

// =============== START reactor class Source
#line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
typedef struct {
#line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int* value;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    bool is_present;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int num_destinations;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    lf_token_t* token;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int length;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
} source_out_t;
typedef struct {
    int bank_index;
    #line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    source_out_t __out;
    #line 5 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    int __out__width;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    reaction_t ___reaction_0;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args;
    source_out_t* out = &self->__out;
    #line 7 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    // Dynamically allocate an output array of length 3.
    SET_NEW_ARRAY(out, 3);
    
    // Above allocates the array, which then must be populated.
    out->value[0] = 0;
    out->value[1] = 1;
    out->value[2] = 2;
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)calloc(1, sizeof(source_self_t));
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.number = 0;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.function = sourcereaction_function_0;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.self = self;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayPrint.lf"
    self->___reaction_0.tardy_handler = NULL;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    return self;
}
void delete_Source(source_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Source

// =============== START reactor class ArrayPrint
typedef struct {
    int bank_index;
} arrayprint_self_t;
arrayprint_self_t* new_ArrayPrint() {
    arrayprint_self_t* self = (arrayprint_self_t*)calloc(1, sizeof(arrayprint_self_t));
    return self;
}
void delete_ArrayPrint(arrayprint_self_t* self) {
    free(self);
}
// =============== END reactor class ArrayPrint

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 1;
    __tokens_with_ref_count = (token_present_t*)malloc(1 * sizeof(token_present_t));
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance ArrayPrint of class ArrayPrint
    arrayprint_self_t* arrayprint_self = new_ArrayPrint();
    //***** Start initializing ArrayPrint
    // ************* Instance ArrayPrint.s of class Source
    source_self_t* arrayprint_s_self = new_Source();
    //***** Start initializing ArrayPrint.s
    // width of -2 indicates that it is not a multiport.
    arrayprint_s_self->__out__width = -2;
    __startup_reactions[0] = &arrayprint_s_self->___reaction_0;
    //***** End initializing ArrayPrint.s
    // ************* Instance ArrayPrint.p of class Print
    print_self_t* arrayprint_p_self = new_Print();
    //***** Start initializing ArrayPrint.p
    arrayprint_p_self->scale = 1; 
    // width of -2 indicates that it is not a multiport.
    arrayprint_p_self->__in__width = -2;
    //***** End initializing ArrayPrint.p
    //***** End initializing ArrayPrint
    // Populate arrays of trigger pointers.
    arrayprint_self->bank_index = 0;
    arrayprint_s_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    arrayprint_s_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (arrayprint_s_self->___reaction_0.num_outputs > 0) {
        arrayprint_s_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * arrayprint_s_self->___reaction_0.num_outputs);
        arrayprint_s_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * arrayprint_s_self->___reaction_0.num_outputs);
        arrayprint_s_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * arrayprint_s_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    arrayprint_s_self->___reaction_0.output_produced[0]
    = &arrayprint_s_self->__out.is_present
    ;
    // Reaction 0 of ArrayPrint.s does not depend on one maximal upstream reaction.
    arrayprint_s_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of ArrayPrint.s triggers 1 downstream reactions through port ArrayPrint.s.out.
    arrayprint_s_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of ArrayPrint.s, allocate an
    // array of trigger pointers for downstream reactions through port ArrayPrint.s.out
    trigger_t** arrayprint_s_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    arrayprint_s_self->___reaction_0.triggers[0] = arrayprint_s_0_0;
    // Point to destination port ArrayPrint.p.in's trigger struct.
    arrayprint_s_0_0[0] = &arrayprint_p_self->___in;
    arrayprint_s_self->__out.num_destinations
    = 1;
    arrayprint_p_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    arrayprint_p_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (arrayprint_p_self->___reaction_0.num_outputs > 0) {
        arrayprint_p_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * arrayprint_p_self->___reaction_0.num_outputs);
        arrayprint_p_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * arrayprint_p_self->___reaction_0.num_outputs);
        arrayprint_p_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * arrayprint_p_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of ArrayPrint.p depends on one maximal upstream reaction.
    arrayprint_p_self->___reaction_0.last_enabling_reaction = &(arrayprint_s_self->___reaction_0);
    // doDeferredInitialize
    arrayprint_s_self->__out.token = __create_token(sizeof(int));
    // Connect inputs and outputs for reactor ArrayPrint.
    // Connect ArrayPrint.s.out to input port ArrayPrint.p.in
    arrayprint_p_self->__in = (print_in_t*)&arrayprint_s_self->__out;
    // Connect inputs and outputs for reactor ArrayPrint.s.
    // END Connect inputs and outputs for reactor ArrayPrint.s.
    // Connect inputs and outputs for reactor ArrayPrint.p.
    // END Connect inputs and outputs for reactor ArrayPrint.p.
    // END Connect inputs and outputs for reactor ArrayPrint.
    __tokens_with_ref_count[0].token
            = &arrayprint_p_self->__in->token;
    __tokens_with_ref_count[0].is_present
            = &arrayprint_p_self->__in->is_present;
    __tokens_with_ref_count[0].reset_is_present = false;
    // Add port ArrayPrint.s.out to array of is_present fields.
    __is_present_fields[0] = &arrayprint_s_self->__out.is_present
    ;
    arrayprint_s_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    arrayprint_s_self->___reaction_0.index = 0x7fffffffffff0000LL;
    arrayprint_p_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    arrayprint_p_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
