#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/ArrayAsType.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Print
#line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
typedef struct {
#line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int value[3];
#line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    bool is_present;
#line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int num_destinations;
#line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
} print_in_t;
typedef struct {
    int bank_index;
    #line 14 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int scale;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    print_in_t* __in;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    // width of -2 indicates that it is not a multiport.
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int __in__width;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    // Default input (in case it does not get connected)
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    print_in_t __default__in;
    #line 16 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    reaction_t ___reaction_0;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    trigger_t ___in;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    reaction_t* ___in_reactions[1];
} print_self_t;
void printreaction_function_0(void* instance_args) {
    print_self_t* self = (print_self_t*)instance_args;
    print_in_t* in = self->__in;
    int in_width = self->__in__width;
    #line 17 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int count = 0;       // For testing.
    bool failed = false; // For testing.
    printf("Received: [");
    for (int i = 0; i < 3; i++) {
        if (i > 0) printf(", ");
        printf("%d", in->value[i]);
        // For testing, check whether values match expectation.
        if (in->value[i] != self->scale * count) {
            failed = true;
        }
        count++;         // For testing.
    }
    printf("]\n");
    if (failed) {
        printf("ERROR: Value received by Print does not match expectation!\n");
        exit(1);
    }
        
}
print_self_t* new_Print() {
    print_self_t* self = (print_self_t*)calloc(1, sizeof(print_self_t));
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    // Set input by default to an always absent default input.
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->__in = &self->__default__in;
    #line 16 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.number = 0;
    #line 16 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.function = printreaction_function_0;
    #line 16 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.self = self;
    #line 16 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 16 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___in.last = NULL;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 15 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(int);
    return self;
}
void delete_Print(print_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Print

// =============== START reactor class Source
#line 5 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
typedef struct {
#line 5 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int value[3];
#line 5 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    bool is_present;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int num_destinations;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
} source_out_t;
typedef struct {
    int bank_index;
    #line 5 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    source_out_t __out;
    #line 5 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    int __out__width;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    reaction_t ___reaction_0;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args;
    source_out_t* out = &self->__out;
    #line 7 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    out->value[0] = 0;
    out->value[1] = 1;
    out->value[2] = 2;
    SET_PRESENT(out);
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)calloc(1, sizeof(source_self_t));
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.number = 0;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.function = sourcereaction_function_0;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.self = self;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayAsType.lf"
    self->___reaction_0.tardy_handler = NULL;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    return self;
}
void delete_Source(source_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Source

// =============== START reactor class ArrayAsType
typedef struct {
    int bank_index;
} arrayastype_self_t;
arrayastype_self_t* new_ArrayAsType() {
    arrayastype_self_t* self = (arrayastype_self_t*)calloc(1, sizeof(arrayastype_self_t));
    return self;
}
void delete_ArrayAsType(arrayastype_self_t* self) {
    free(self);
}
// =============== END reactor class ArrayAsType

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance ArrayAsType of class ArrayAsType
    arrayastype_self_t* arrayastype_self = new_ArrayAsType();
    //***** Start initializing ArrayAsType
    // ************* Instance ArrayAsType.s of class Source
    source_self_t* arrayastype_s_self = new_Source();
    //***** Start initializing ArrayAsType.s
    // width of -2 indicates that it is not a multiport.
    arrayastype_s_self->__out__width = -2;
    __startup_reactions[0] = &arrayastype_s_self->___reaction_0;
    //***** End initializing ArrayAsType.s
    // ************* Instance ArrayAsType.p of class Print
    print_self_t* arrayastype_p_self = new_Print();
    //***** Start initializing ArrayAsType.p
    arrayastype_p_self->scale = 1; 
    // width of -2 indicates that it is not a multiport.
    arrayastype_p_self->__in__width = -2;
    //***** End initializing ArrayAsType.p
    //***** End initializing ArrayAsType
    // Populate arrays of trigger pointers.
    arrayastype_self->bank_index = 0;
    arrayastype_s_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    arrayastype_s_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (arrayastype_s_self->___reaction_0.num_outputs > 0) {
        arrayastype_s_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * arrayastype_s_self->___reaction_0.num_outputs);
        arrayastype_s_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * arrayastype_s_self->___reaction_0.num_outputs);
        arrayastype_s_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * arrayastype_s_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    arrayastype_s_self->___reaction_0.output_produced[0]
    = &arrayastype_s_self->__out.is_present
    ;
    // Reaction 0 of ArrayAsType.s does not depend on one maximal upstream reaction.
    arrayastype_s_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of ArrayAsType.s triggers 1 downstream reactions through port ArrayAsType.s.out.
    arrayastype_s_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of ArrayAsType.s, allocate an
    // array of trigger pointers for downstream reactions through port ArrayAsType.s.out
    trigger_t** arrayastype_s_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    arrayastype_s_self->___reaction_0.triggers[0] = arrayastype_s_0_0;
    // Point to destination port ArrayAsType.p.in's trigger struct.
    arrayastype_s_0_0[0] = &arrayastype_p_self->___in;
    arrayastype_s_self->__out.num_destinations
    = 1;
    arrayastype_p_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    arrayastype_p_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (arrayastype_p_self->___reaction_0.num_outputs > 0) {
        arrayastype_p_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * arrayastype_p_self->___reaction_0.num_outputs);
        arrayastype_p_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * arrayastype_p_self->___reaction_0.num_outputs);
        arrayastype_p_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * arrayastype_p_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of ArrayAsType.p depends on one maximal upstream reaction.
    arrayastype_p_self->___reaction_0.last_enabling_reaction = &(arrayastype_s_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor ArrayAsType.
    // Connect ArrayAsType.s.out to input port ArrayAsType.p.in
    arrayastype_p_self->__in = (print_in_t*)&arrayastype_s_self->__out;
    // Connect inputs and outputs for reactor ArrayAsType.s.
    // END Connect inputs and outputs for reactor ArrayAsType.s.
    // Connect inputs and outputs for reactor ArrayAsType.p.
    // END Connect inputs and outputs for reactor ArrayAsType.p.
    // END Connect inputs and outputs for reactor ArrayAsType.
    // Add port ArrayAsType.s.out to array of is_present fields.
    __is_present_fields[0] = &arrayastype_s_self->__out.is_present
    ;
    arrayastype_s_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    arrayastype_s_self->___reaction_0.index = 0x7fffffffffff0000LL;
    arrayastype_p_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    arrayastype_p_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
