#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/ArrayScale.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Print
#line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
typedef struct {
#line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int* value;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    bool is_present;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int num_destinations;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    lf_token_t* token;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int length;
#line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
} print_in_t;
typedef struct {
    int bank_index;
    #line 17 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int scale;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    print_in_t* __in;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    // width of -2 indicates that it is not a multiport.
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int __in__width;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    // Default input (in case it does not get connected)
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    print_in_t __default__in;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    reaction_t ___reaction_0;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    trigger_t ___in;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    reaction_t* ___in_reactions[1];
} print_self_t;
void printreaction_function_0(void* instance_args) {
    print_self_t* self = (print_self_t*)instance_args;
    print_in_t* in = self->__in;
    if (in->is_present) {
        in->length = in->token->length;
        in->value = (int*)in->token->value;
    } else {
        in->length = 0;
    }
    int in_width = self->__in__width;
    #line 20 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int count = 0;       // For testing.
    bool failed = false; // For testing.
    printf("Received: [");
    for (int i = 0; i < in->length; i++) {
        if (i > 0) printf(", ");
        printf("%d", in->value[i]);
        // For testing, check whether values match expectation.
        if (in->value[i] != self->scale * count) {
            failed = true;
        }
        count++;         // For testing.
    }
    printf("]\n");
    if (failed) {
        printf("ERROR: Value received by Print does not match expectation!\n");
        exit(1);
    }
        
}
print_self_t* new_Print() {
    print_self_t* self = (print_self_t*)calloc(1, sizeof(print_self_t));
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    // Set input by default to an always absent default input.
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->__in = &self->__default__in;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.number = 0;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.function = printreaction_function_0;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.self = self;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 19 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in.last = NULL;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 18 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(int);
    return self;
}
void delete_Print(print_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Print

// =============== START reactor class Scale
#line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
typedef struct {
#line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int* value;
#line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    bool is_present;
#line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int num_destinations;
#line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    lf_token_t* token;
#line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int length;
#line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
} scale_in_t;
#line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
typedef struct {
#line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int* value;
#line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    bool is_present;
#line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int num_destinations;
#line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    lf_token_t* token;
#line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int length;
#line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
} scale_out_t;
typedef struct {
    int bank_index;
    #line 9 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int scale;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    scale_in_t* __in;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    // width of -2 indicates that it is not a multiport.
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int __in__width;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    // Default input (in case it does not get connected)
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    scale_in_t __default__in;
    #line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    scale_out_t __out;
    #line 11 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int __out__width;
    #line 12 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    reaction_t ___reaction_0;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    trigger_t ___in;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    reaction_t* ___in_reactions[1];
} scale_self_t;
void scalereaction_function_0(void* instance_args) {
    scale_self_t* self = (scale_self_t*)instance_args;
    // Mutable input, so copy the input struct into a temporary variable.
    scale_in_t __tmp_in = *(self->__in);
    scale_in_t* in = &__tmp_in;
    if (in->is_present) {
        in->length = in->token->length;
        lf_token_t* _lf_input_token = in->token;
        in->token = writable_copy(_lf_input_token);
        if (in->token != _lf_input_token) {
            // A copy of the input token has been made.
            // This needs to be reference counted.
            in->token->ref_count = 1;
            // Repurpose the next_free pointer on the token to add to the list.
            in->token->next_free = _lf_more_tokens_with_ref_count;
            _lf_more_tokens_with_ref_count = in->token;
        }
        in->value = (int*)in->token->value;
    } else {
        in->length = 0;
    }
    int in_width = self->__in__width;
    scale_out_t* out = &self->__out;
    #line 13 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    for(int i = 0; i < in->length; i++) {
        in->value[i] *= self->scale;
    }
    SET_TOKEN(out, in->token);
        
}
scale_self_t* new_Scale() {
    scale_self_t* self = (scale_self_t*)calloc(1, sizeof(scale_self_t));
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    // Set input by default to an always absent default input.
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->__in = &self->__default__in;
    #line 12 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.number = 0;
    #line 12 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.function = scalereaction_function_0;
    #line 12 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.self = self;
    #line 12 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 12 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in.last = NULL;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 10 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(int);
    return self;
}
void delete_Scale(scale_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Scale

// =============== START reactor class Source
#line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
typedef struct {
#line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int* value;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    bool is_present;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int num_destinations;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    lf_token_t* token;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int length;
#line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
} source_out_t;
typedef struct {
    int bank_index;
    #line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    source_out_t __out;
    #line 5 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    int __out__width;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    reaction_t ___reaction_0;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args;
    source_out_t* out = &self->__out;
    #line 7 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    // Dynamically allocate an output array of length 3.
    SET_NEW_ARRAY(out, 3);
    
    // Above allocates the array, which then must be populated.
    out->value[0] = 0;
    out->value[1] = 1;
    out->value[2] = 2;
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)calloc(1, sizeof(source_self_t));
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.number = 0;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.function = sourcereaction_function_0;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.self = self;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 6 "file:/lf-flexpret-scripts/tests/ArrayScale.lf"
    self->___reaction_0.tardy_handler = NULL;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    return self;
}
void delete_Source(source_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Source

// =============== START reactor class ArrayScale
typedef struct {
    int bank_index;
} arrayscale_self_t;
arrayscale_self_t* new_ArrayScale() {
    arrayscale_self_t* self = (arrayscale_self_t*)calloc(1, sizeof(arrayscale_self_t));
    return self;
}
void delete_ArrayScale(arrayscale_self_t* self) {
    free(self);
}
// =============== END reactor class ArrayScale

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 2;
    __tokens_with_ref_count = (token_present_t*)malloc(2 * sizeof(token_present_t));
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 2;
    __is_present_fields = (bool**)malloc(2 * sizeof(bool*));
    // ************* Instance ArrayScale of class ArrayScale
    arrayscale_self_t* arrayscale_self = new_ArrayScale();
    //***** Start initializing ArrayScale
    // ************* Instance ArrayScale.s of class Source
    source_self_t* arrayscale_s_self = new_Source();
    //***** Start initializing ArrayScale.s
    // width of -2 indicates that it is not a multiport.
    arrayscale_s_self->__out__width = -2;
    __startup_reactions[0] = &arrayscale_s_self->___reaction_0;
    //***** End initializing ArrayScale.s
    // ************* Instance ArrayScale.c of class Scale
    scale_self_t* arrayscale_c_self = new_Scale();
    //***** Start initializing ArrayScale.c
    arrayscale_c_self->scale = 2; 
    // width of -2 indicates that it is not a multiport.
    arrayscale_c_self->__out__width = -2;
    // width of -2 indicates that it is not a multiport.
    arrayscale_c_self->__in__width = -2;
    //***** End initializing ArrayScale.c
    // ************* Instance ArrayScale.p of class Print
    print_self_t* arrayscale_p_self = new_Print();
    //***** Start initializing ArrayScale.p
    arrayscale_p_self->scale = 2; 
    // width of -2 indicates that it is not a multiport.
    arrayscale_p_self->__in__width = -2;
    //***** End initializing ArrayScale.p
    //***** End initializing ArrayScale
    // Populate arrays of trigger pointers.
    arrayscale_self->bank_index = 0;
    arrayscale_s_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    arrayscale_s_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (arrayscale_s_self->___reaction_0.num_outputs > 0) {
        arrayscale_s_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * arrayscale_s_self->___reaction_0.num_outputs);
        arrayscale_s_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * arrayscale_s_self->___reaction_0.num_outputs);
        arrayscale_s_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * arrayscale_s_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    arrayscale_s_self->___reaction_0.output_produced[0]
    = &arrayscale_s_self->__out.is_present
    ;
    // Reaction 0 of ArrayScale.s does not depend on one maximal upstream reaction.
    arrayscale_s_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of ArrayScale.s triggers 1 downstream reactions through port ArrayScale.s.out.
    arrayscale_s_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of ArrayScale.s, allocate an
    // array of trigger pointers for downstream reactions through port ArrayScale.s.out
    trigger_t** arrayscale_s_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    arrayscale_s_self->___reaction_0.triggers[0] = arrayscale_s_0_0;
    // Point to destination port ArrayScale.c.in's trigger struct.
    arrayscale_s_0_0[0] = &arrayscale_c_self->___in;
    arrayscale_s_self->__out.num_destinations
    = 1;
    arrayscale_c_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    arrayscale_c_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (arrayscale_c_self->___reaction_0.num_outputs > 0) {
        arrayscale_c_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * arrayscale_c_self->___reaction_0.num_outputs);
        arrayscale_c_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * arrayscale_c_self->___reaction_0.num_outputs);
        arrayscale_c_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * arrayscale_c_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    arrayscale_c_self->___reaction_0.output_produced[0]
    = &arrayscale_c_self->__out.is_present
    ;
    // Reaction 0 of ArrayScale.c depends on one maximal upstream reaction.
    arrayscale_c_self->___reaction_0.last_enabling_reaction = &(arrayscale_s_self->___reaction_0);
    // Reaction 0 of ArrayScale.c triggers 1 downstream reactions through port ArrayScale.c.out.
    arrayscale_c_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of ArrayScale.c, allocate an
    // array of trigger pointers for downstream reactions through port ArrayScale.c.out
    trigger_t** arrayscale_c_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    arrayscale_c_self->___reaction_0.triggers[0] = arrayscale_c_0_0;
    // Point to destination port ArrayScale.p.in's trigger struct.
    arrayscale_c_0_0[0] = &arrayscale_p_self->___in;
    arrayscale_c_self->__out.num_destinations
    = 1;
    arrayscale_p_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    arrayscale_p_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (arrayscale_p_self->___reaction_0.num_outputs > 0) {
        arrayscale_p_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * arrayscale_p_self->___reaction_0.num_outputs);
        arrayscale_p_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * arrayscale_p_self->___reaction_0.num_outputs);
        arrayscale_p_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * arrayscale_p_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of ArrayScale.p depends on one maximal upstream reaction.
    arrayscale_p_self->___reaction_0.last_enabling_reaction = &(arrayscale_c_self->___reaction_0);
    // doDeferredInitialize
    arrayscale_s_self->__out.token = __create_token(sizeof(int));
    arrayscale_c_self->__out.token = __create_token(sizeof(int));
    // Connect inputs and outputs for reactor ArrayScale.
    // Connect ArrayScale.s.out to input port ArrayScale.c.in
    arrayscale_c_self->__in = (scale_in_t*)&arrayscale_s_self->__out;
    // Connect ArrayScale.c.out to input port ArrayScale.p.in
    arrayscale_p_self->__in = (print_in_t*)&arrayscale_c_self->__out;
    // Connect inputs and outputs for reactor ArrayScale.s.
    // END Connect inputs and outputs for reactor ArrayScale.s.
    // Connect inputs and outputs for reactor ArrayScale.c.
    // END Connect inputs and outputs for reactor ArrayScale.c.
    // Connect inputs and outputs for reactor ArrayScale.p.
    // END Connect inputs and outputs for reactor ArrayScale.p.
    // END Connect inputs and outputs for reactor ArrayScale.
    __tokens_with_ref_count[0].token
            = &arrayscale_c_self->__in->token;
    __tokens_with_ref_count[0].is_present
            = &arrayscale_c_self->__in->is_present;
    __tokens_with_ref_count[0].reset_is_present = false;
    __tokens_with_ref_count[1].token
            = &arrayscale_p_self->__in->token;
    __tokens_with_ref_count[1].is_present
            = &arrayscale_p_self->__in->is_present;
    __tokens_with_ref_count[1].reset_is_present = false;
    // Add port ArrayScale.s.out to array of is_present fields.
    __is_present_fields[0] = &arrayscale_s_self->__out.is_present
    ;
    // Add port ArrayScale.c.out to array of is_present fields.
    __is_present_fields[1] = &arrayscale_c_self->__out.is_present
    ;
    arrayscale_s_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    arrayscale_s_self->___reaction_0.index = 0x7fffffffffff0000LL;
    arrayscale_c_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    arrayscale_c_self->___reaction_0.index = 0x7fffffffffff0001LL;
    arrayscale_p_self->___reaction_0.chain_id = 1;
    // index is the OR of level 2 and 
    // deadline 140737488355327 shifted left 16 bits.
    arrayscale_p_self->___reaction_0.index = 0x7fffffffffff0002LL;
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
