#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/DanglingOutput.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Gain
#line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
typedef struct {
#line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int value;
#line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    bool is_present;
#line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int num_destinations;
#line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
} gain_in_t;
#line 14 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
typedef struct {
#line 14 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int value;
#line 14 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    bool is_present;
#line 14 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int num_destinations;
#line 14 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
} gain_out_t;
typedef struct {
    int bank_index;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    gain_in_t* __in;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    // width of -2 indicates that it is not a multiport.
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int __in__width;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    // Default input (in case it does not get connected)
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    gain_in_t __default__in;
    #line 14 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    gain_out_t __out;
    #line 14 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int __out__width;
    #line 15 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    reaction_t ___reaction_0;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    trigger_t ___in;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    reaction_t* ___in_reactions[1];
} gain_self_t;
void gainreaction_function_0(void* instance_args) {
    gain_self_t* self = (gain_self_t*)instance_args;
    gain_in_t* in = self->__in;
    int in_width = self->__in__width;
    gain_out_t* out = &self->__out;
    #line 16 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    printf("Received %d.\n", in->value);
    SET(out, in->value * 2);
        
}
gain_self_t* new_Gain() {
    gain_self_t* self = (gain_self_t*)calloc(1, sizeof(gain_self_t));
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    // Set input by default to an always absent default input.
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->__in = &self->__default__in;
    #line 15 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.number = 0;
    #line 15 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.function = gainreaction_function_0;
    #line 15 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.self = self;
    #line 15 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 15 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___in.last = NULL;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 13 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(int);
    return self;
}
void delete_Gain(gain_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Gain

// =============== START reactor class Source
#line 5 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
typedef struct {
#line 5 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int value;
#line 5 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    bool is_present;
#line 5 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int num_destinations;
#line 5 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
} source_out_t;
typedef struct {
    int bank_index;
    #line 5 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    source_out_t __out;
    #line 5 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    int __out__width;
    #line 7 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    reaction_t ___reaction_0;
    #line 6 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    trigger_t ___t;
    #line 6 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    reaction_t* ___t_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args;
    source_out_t* out = &self->__out;
    #line 8 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    SET(out, 1);
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)calloc(1, sizeof(source_self_t));
    #line 7 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.number = 0;
    #line 7 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.function = sourcereaction_function_0;
    #line 7 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.self = self;
    #line 7 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 7 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 6 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___t.last = NULL;
    #line 6 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    #line 6 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___t_reactions[0] = &self->___reaction_0;
    #line 6 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___t.reactions = &self->___t_reactions[0];
    #line 6 "file:/lf-flexpret-scripts/tests/DanglingOutput.lf"
    self->___t.number_of_reactions = 1;
    self->___t.is_timer = true;
    return self;
}
void delete_Source(source_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Source

// =============== START reactor class DanglingOutput
typedef struct {
    int bank_index;
} danglingoutput_self_t;
danglingoutput_self_t* new_DanglingOutput() {
    danglingoutput_self_t* self = (danglingoutput_self_t*)calloc(1, sizeof(danglingoutput_self_t));
    return self;
}
void delete_DanglingOutput(danglingoutput_self_t* self) {
    free(self);
}
// =============== END reactor class DanglingOutput

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
// Array of pointers to reactions to be scheduled in __trigger_startup_reactions().
reaction_t** __startup_reactions = NULL;
int __startup_reactions_size = 0;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 2;
    __is_present_fields = (bool**)malloc(2 * sizeof(bool*));
    // ************* Instance DanglingOutput of class DanglingOutput
    danglingoutput_self_t* danglingoutput_self = new_DanglingOutput();
    //***** Start initializing DanglingOutput
    // ************* Instance DanglingOutput.source of class Source
    source_self_t* danglingoutput_source_self = new_Source();
    //***** Start initializing DanglingOutput.source
    // width of -2 indicates that it is not a multiport.
    danglingoutput_source_self->__out__width = -2;
    danglingoutput_source_self->___t.offset = 0;
    danglingoutput_source_self->___t.period = 0;
    __timer_triggers[0] = &danglingoutput_source_self->___t;
    //***** End initializing DanglingOutput.source
    // ************* Instance DanglingOutput.container of class Gain
    gain_self_t* danglingoutput_container_self = new_Gain();
    //***** Start initializing DanglingOutput.container
    // width of -2 indicates that it is not a multiport.
    danglingoutput_container_self->__out__width = -2;
    // width of -2 indicates that it is not a multiport.
    danglingoutput_container_self->__in__width = -2;
    //***** End initializing DanglingOutput.container
    //***** End initializing DanglingOutput
    // Populate arrays of trigger pointers.
    danglingoutput_self->bank_index = 0;
    danglingoutput_source_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    danglingoutput_source_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (danglingoutput_source_self->___reaction_0.num_outputs > 0) {
        danglingoutput_source_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * danglingoutput_source_self->___reaction_0.num_outputs);
        danglingoutput_source_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * danglingoutput_source_self->___reaction_0.num_outputs);
        danglingoutput_source_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * danglingoutput_source_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    danglingoutput_source_self->___reaction_0.output_produced[0]
    = &danglingoutput_source_self->__out.is_present
    ;
    // Reaction 0 of DanglingOutput.source does not depend on one maximal upstream reaction.
    danglingoutput_source_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of DanglingOutput.source triggers 1 downstream reactions through port DanglingOutput.source.out.
    danglingoutput_source_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of DanglingOutput.source, allocate an
    // array of trigger pointers for downstream reactions through port DanglingOutput.source.out
    trigger_t** danglingoutput_source_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    danglingoutput_source_self->___reaction_0.triggers[0] = danglingoutput_source_0_0;
    // Point to destination port DanglingOutput.container.in's trigger struct.
    danglingoutput_source_0_0[0] = &danglingoutput_container_self->___in;
    danglingoutput_source_self->__out.num_destinations
    = 1;
    danglingoutput_container_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    danglingoutput_container_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (danglingoutput_container_self->___reaction_0.num_outputs > 0) {
        danglingoutput_container_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * danglingoutput_container_self->___reaction_0.num_outputs);
        danglingoutput_container_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * danglingoutput_container_self->___reaction_0.num_outputs);
        danglingoutput_container_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * danglingoutput_container_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    danglingoutput_container_self->___reaction_0.output_produced[0]
    = &danglingoutput_container_self->__out.is_present
    ;
    // Reaction 0 of DanglingOutput.container depends on one maximal upstream reaction.
    danglingoutput_container_self->___reaction_0.last_enabling_reaction = &(danglingoutput_source_self->___reaction_0);
    // Reaction 0 of DanglingOutput.container triggers 0 downstream reactions through port DanglingOutput.container.out.
    danglingoutput_container_self->___reaction_0.triggered_sizes[0] = 0;
    danglingoutput_container_self->__out.num_destinations
    = 0;
    // doDeferredInitialize
    // Connect inputs and outputs for reactor DanglingOutput.
    // Connect DanglingOutput.source.out to input port DanglingOutput.container.in
    danglingoutput_container_self->__in = (gain_in_t*)&danglingoutput_source_self->__out;
    // Connect inputs and outputs for reactor DanglingOutput.source.
    // END Connect inputs and outputs for reactor DanglingOutput.source.
    // Connect inputs and outputs for reactor DanglingOutput.container.
    // END Connect inputs and outputs for reactor DanglingOutput.container.
    // END Connect inputs and outputs for reactor DanglingOutput.
    // Add port DanglingOutput.source.out to array of is_present fields.
    __is_present_fields[0] = &danglingoutput_source_self->__out.is_present
    ;
    // Add port DanglingOutput.container.out to array of is_present fields.
    __is_present_fields[1] = &danglingoutput_container_self->__out.is_present
    ;
    danglingoutput_source_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    danglingoutput_source_self->___reaction_0.index = 0x7fffffffffff0000LL;
    danglingoutput_container_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    danglingoutput_container_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
}
void __initialize_timers() {
    for (int i = 0; i < __timer_triggers_size; i++) {
        if (__timer_triggers[i] != NULL) {
            _lf_initialize_timer(__timer_triggers[i]);
        }
    }
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
