#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/Deadline.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Destination
#line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
typedef struct {
#line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int value;
#line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    bool is_present;
#line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int num_destinations;
#line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
} destination_x_t;
typedef struct {
    int bank_index;
    #line 27 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    interval_t timeout;
    #line 29 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int count;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    destination_x_t* __x;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    // width of -2 indicates that it is not a multiport.
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int __x__width;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    // Default input (in case it does not get connected)
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    destination_x_t __default__x;
    #line 30 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    reaction_t ___reaction_0;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    trigger_t ___x;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    reaction_t* ___x_reactions[1];
} destination_self_t;
void destinationreaction_function_0(void* instance_args) {
    destination_self_t* self = (destination_self_t*)instance_args;
    destination_x_t* x = self->__x;
    int x_width = self->__x__width;
    #line 31 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    printf("Destination receives: %d\n", x->value);
    if (2 * (self->count / 2) != self->count) {
        // The count variable is odd, so the deadline should have been violated.
        printf("ERROR: Failed to detect deadline.\n");
        exit(1);
    }
    (self->count)++;
        
}
void destination_deadline_function0(void* instance_args) {
    destination_self_t* self = (destination_self_t*)instance_args;
    destination_x_t* x = self->__x;
    int x_width = self->__x__width;
    #line 39 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    printf("Destination deadline handler receives: %d\n", x->value);
    if (2 * (self->count / 2) == self->count) {
        // The count variable is even, so the deadline should not have been violated.
        printf("ERROR: Deadline miss handler invoked without deadline violation.\n");
        exit(2);
    }
    (self->count)++;
        
}
destination_self_t* new_Destination() {
    destination_self_t* self = (destination_self_t*)calloc(1, sizeof(destination_self_t));
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    // Set input by default to an always absent default input.
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->__x = &self->__default__x;
    #line 30 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.number = 0;
    #line 30 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.function = destinationreaction_function_0;
    #line 30 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.self = self;
    #line 30 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.deadline_violation_handler = &destination_deadline_function0;
    #line 30 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___x.last = NULL;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___x_reactions[0] = &self->___reaction_0;
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___x.reactions = &self->___x_reactions[0];
    #line 28 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___x.number_of_reactions = 1;
    self->___x.element_size = sizeof(int);
    return self;
}
void delete_Destination(destination_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Destination

// =============== START reactor class Source
#line 8 "file:/lf-flexpret-scripts/tests/Deadline.lf"
typedef struct {
#line 8 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int value;
#line 8 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    bool is_present;
#line 8 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int num_destinations;
#line 8 "file:/lf-flexpret-scripts/tests/Deadline.lf"
} source_y_t;
typedef struct {
    int bank_index;
    #line 7 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    interval_t period;
    #line 10 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int count;
    #line 8 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    source_y_t __y;
    #line 8 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    int __y__width;
    #line 11 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    reaction_t ___reaction_0;
    #line 9 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    trigger_t ___t;
    #line 9 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    reaction_t* ___t_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args;
    source_y_t* y = &self->__y;
    #line 12 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    if (2 * (self->count / 2) != self->count) {
        // The count variable is odd.
        // Take time to cause a deadline violation.
        // Do not use nanosleep() here because if this is threaded,
        // it gets awakened right away.
        interval_t sleep_time = MSEC(200);
        instant_t start_time = get_physical_time();
        while (get_physical_time() < start_time + sleep_time) {};
    }
    printf("Source sends: %d.\n", self->count);
    SET(y, self->count);
    (self->count)++;
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)calloc(1, sizeof(source_self_t));
    #line 11 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.number = 0;
    #line 11 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.function = sourcereaction_function_0;
    #line 11 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.self = self;
    #line 11 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 11 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 9 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___t.last = NULL;
    #line 9 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    #line 9 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___t_reactions[0] = &self->___reaction_0;
    #line 9 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___t.reactions = &self->___t_reactions[0];
    #line 9 "file:/lf-flexpret-scripts/tests/Deadline.lf"
    self->___t.number_of_reactions = 1;
    self->___t.is_timer = true;
    return self;
}
void delete_Source(source_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Source

// =============== START reactor class Deadline
typedef struct {
    int bank_index;
} deadline_self_t;
deadline_self_t* new_Deadline() {
    deadline_self_t* self = (deadline_self_t*)calloc(1, sizeof(deadline_self_t));
    return self;
}
void delete_Deadline(deadline_self_t* self) {
    free(self);
}
// =============== END reactor class Deadline

char* __default_argv[] = {"X", "-o", "2", "sec"};
void __set_default_command_line_options() {
    default_argc = 4;
    default_argv = __default_argv;
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
// Array of pointers to reactions to be scheduled in __trigger_startup_reactions().
reaction_t** __startup_reactions = NULL;
int __startup_reactions_size = 0;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance Deadline of class Deadline
    deadline_self_t* deadline_self = new_Deadline();
    //***** Start initializing Deadline
    // ************* Instance Deadline.s of class Source
    source_self_t* deadline_s_self = new_Source();
    //***** Start initializing Deadline.s
    deadline_s_self->period = SEC(1); 
    // width of -2 indicates that it is not a multiport.
    deadline_s_self->__y__width = -2;
    static int deadline_s_initial_count = 0;
    deadline_s_self->count = deadline_s_initial_count;
    deadline_s_self->___t.offset = 0;
    deadline_s_self->___t.period = SEC(1);
    __timer_triggers[0] = &deadline_s_self->___t;
    //***** End initializing Deadline.s
    // ************* Instance Deadline.d of class Destination
    destination_self_t* deadline_d_self = new_Destination();
    //***** Start initializing Deadline.d
    deadline_d_self->timeout = MSEC(100); 
    // width of -2 indicates that it is not a multiport.
    deadline_d_self->__x__width = -2;
    static int deadline_d_initial_count = 0;
    deadline_d_self->count = deadline_d_initial_count;
    deadline_d_self->___reaction_0.deadline = MSEC(100);
    //***** End initializing Deadline.d
    //***** End initializing Deadline
    // Populate arrays of trigger pointers.
    deadline_self->bank_index = 0;
    deadline_s_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    deadline_s_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (deadline_s_self->___reaction_0.num_outputs > 0) {
        deadline_s_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * deadline_s_self->___reaction_0.num_outputs);
        deadline_s_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * deadline_s_self->___reaction_0.num_outputs);
        deadline_s_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * deadline_s_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    deadline_s_self->___reaction_0.output_produced[0]
    = &deadline_s_self->__y.is_present
    ;
    // Reaction 0 of Deadline.s does not depend on one maximal upstream reaction.
    deadline_s_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of Deadline.s triggers 1 downstream reactions through port Deadline.s.y.
    deadline_s_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Deadline.s, allocate an
    // array of trigger pointers for downstream reactions through port Deadline.s.y
    trigger_t** deadline_s_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    deadline_s_self->___reaction_0.triggers[0] = deadline_s_0_0;
    // Point to destination port Deadline.d.x's trigger struct.
    deadline_s_0_0[0] = &deadline_d_self->___x;
    deadline_s_self->__y.num_destinations
    = 1;
    deadline_d_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    deadline_d_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (deadline_d_self->___reaction_0.num_outputs > 0) {
        deadline_d_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * deadline_d_self->___reaction_0.num_outputs);
        deadline_d_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * deadline_d_self->___reaction_0.num_outputs);
        deadline_d_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * deadline_d_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of Deadline.d depends on one maximal upstream reaction.
    deadline_d_self->___reaction_0.last_enabling_reaction = &(deadline_s_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor Deadline.
    // Connect Deadline.s.y to input port Deadline.d.x
    deadline_d_self->__x = (destination_x_t*)&deadline_s_self->__y;
    // Connect inputs and outputs for reactor Deadline.s.
    // END Connect inputs and outputs for reactor Deadline.s.
    // Connect inputs and outputs for reactor Deadline.d.
    // END Connect inputs and outputs for reactor Deadline.d.
    // END Connect inputs and outputs for reactor Deadline.
    // Add port Deadline.s.y to array of is_present fields.
    __is_present_fields[0] = &deadline_s_self->__y.is_present
    ;
    deadline_s_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    deadline_s_self->___reaction_0.index = 0x7fffffffffff0000LL;
    deadline_d_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    deadline_d_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
}
void __initialize_timers() {
    for (int i = 0; i < __timer_triggers_size; i++) {
        if (__timer_triggers[i] != NULL) {
            _lf_initialize_timer(__timer_triggers[i]);
        }
    }
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
