#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/DoubleReaction.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Destination
#line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
typedef struct {
#line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int value;
#line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    bool is_present;
#line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int num_destinations;
#line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
} destination_x_t;
#line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
typedef struct {
#line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int value;
#line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    bool is_present;
#line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int num_destinations;
#line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
} destination_w_t;
typedef struct {
    int bank_index;
    #line 21 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int s;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    destination_x_t* __x;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    // width of -2 indicates that it is not a multiport.
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int __x__width;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    // Default input (in case it does not get connected)
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    destination_x_t __default__x;
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    destination_w_t* __w;
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    // width of -2 indicates that it is not a multiport.
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int __w__width;
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    // Default input (in case it does not get connected)
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    destination_w_t __default__w;
    #line 22 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    reaction_t ___reaction_0;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    trigger_t ___x;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    reaction_t* ___x_reactions[1];
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    trigger_t ___w;
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    reaction_t* ___w_reactions[1];
} destination_self_t;
void destinationreaction_function_0(void* instance_args) {
    destination_self_t* self = (destination_self_t*)instance_args;
    destination_x_t* x = self->__x;
    int x_width = self->__x__width;
    destination_w_t* w = self->__w;
    int w_width = self->__w__width;
    #line 23 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int sum = 0;
    if (x->is_present) {
        sum += x->value;
    }
    if (w->is_present) {
        sum += w->value;
    }
    printf("Sum of inputs is: %d\n", sum);
    if (sum != self->s) {
        printf("FAILURE: Expected sum to be %d, but it was %d.\n", self->s, sum);
        exit(1);
    }
    self->s += 2;
        
}
destination_self_t* new_Destination() {
    destination_self_t* self = (destination_self_t*)calloc(1, sizeof(destination_self_t));
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    // Set input by default to an always absent default input.
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->__x = &self->__default__x;
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    // Set input by default to an always absent default input.
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->__w = &self->__default__w;
    #line 22 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.number = 0;
    #line 22 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.function = destinationreaction_function_0;
    #line 22 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.self = self;
    #line 22 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 22 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___x.last = NULL;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___x_reactions[0] = &self->___reaction_0;
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___x.reactions = &self->___x_reactions[0];
    #line 19 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___x.number_of_reactions = 1;
    self->___x.element_size = sizeof(int);
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___w.last = NULL;
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___w_reactions[0] = &self->___reaction_0;
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___w.reactions = &self->___w_reactions[0];
    #line 20 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___w.number_of_reactions = 1;
    self->___w.element_size = sizeof(int);
    return self;
}
void delete_Destination(destination_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Destination

// =============== START reactor class Clock
#line 9 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
typedef struct {
#line 9 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int value;
#line 9 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    bool is_present;
#line 9 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int num_destinations;
#line 9 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
} clock_y_t;
typedef struct {
    int bank_index;
    #line 8 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    interval_t offset;
    #line 8 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    interval_t period;
    #line 11 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int count;
    #line 9 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    clock_y_t __y;
    #line 9 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    int __y__width;
    #line 12 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    reaction_t ___reaction_0;
    #line 10 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    trigger_t ___t;
    #line 10 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    reaction_t* ___t_reactions[1];
} clock_self_t;
void clockreaction_function_0(void* instance_args) {
    clock_self_t* self = (clock_self_t*)instance_args;
    clock_y_t* y = &self->__y;
    #line 13 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    (self->count)++;
    SET(y, self->count);
        
}
clock_self_t* new_Clock() {
    clock_self_t* self = (clock_self_t*)calloc(1, sizeof(clock_self_t));
    #line 12 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.number = 0;
    #line 12 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.function = clockreaction_function_0;
    #line 12 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.self = self;
    #line 12 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 12 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 10 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___t.last = NULL;
    #line 10 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    #line 10 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___t_reactions[0] = &self->___reaction_0;
    #line 10 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___t.reactions = &self->___t_reactions[0];
    #line 10 "file:/lf-flexpret-scripts/tests/DoubleReaction.lf"
    self->___t.number_of_reactions = 1;
    self->___t.is_timer = true;
    return self;
}
void delete_Clock(clock_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Clock

// =============== START reactor class DoubleReaction
typedef struct {
    int bank_index;
} doublereaction_self_t;
doublereaction_self_t* new_DoubleReaction() {
    doublereaction_self_t* self = (doublereaction_self_t*)calloc(1, sizeof(doublereaction_self_t));
    return self;
}
void delete_DoubleReaction(doublereaction_self_t* self) {
    free(self);
}
// =============== END reactor class DoubleReaction

char* __default_argv[] = {"X", "-f", "true", "-o", "10", "sec"};
void __set_default_command_line_options() {
    default_argc = 6;
    default_argv = __default_argv;
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t* __timer_triggers[2];
int __timer_triggers_size = 2;
// Array of pointers to reactions to be scheduled in __trigger_startup_reactions().
reaction_t** __startup_reactions = NULL;
int __startup_reactions_size = 0;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 2;
    __is_present_fields = (bool**)malloc(2 * sizeof(bool*));
    // ************* Instance DoubleReaction of class DoubleReaction
    doublereaction_self_t* doublereaction_self = new_DoubleReaction();
    //***** Start initializing DoubleReaction
    // ************* Instance DoubleReaction.c1 of class Clock
    clock_self_t* doublereaction_c1_self = new_Clock();
    //***** Start initializing DoubleReaction.c1
    doublereaction_c1_self->offset = 0; 
    doublereaction_c1_self->period = SEC(1); 
    // width of -2 indicates that it is not a multiport.
    doublereaction_c1_self->__y__width = -2;
    static int doublereaction_c1_initial_count = 0;
    doublereaction_c1_self->count = doublereaction_c1_initial_count;
    doublereaction_c1_self->___t.offset = 0;
    doublereaction_c1_self->___t.period = SEC(1);
    __timer_triggers[0] = &doublereaction_c1_self->___t;
    //***** End initializing DoubleReaction.c1
    // ************* Instance DoubleReaction.c2 of class Clock
    clock_self_t* doublereaction_c2_self = new_Clock();
    //***** Start initializing DoubleReaction.c2
    doublereaction_c2_self->offset = 0; 
    doublereaction_c2_self->period = SEC(1); 
    // width of -2 indicates that it is not a multiport.
    doublereaction_c2_self->__y__width = -2;
    static int doublereaction_c2_initial_count = 0;
    doublereaction_c2_self->count = doublereaction_c2_initial_count;
    doublereaction_c2_self->___t.offset = 0;
    doublereaction_c2_self->___t.period = SEC(1);
    __timer_triggers[1] = &doublereaction_c2_self->___t;
    //***** End initializing DoubleReaction.c2
    // ************* Instance DoubleReaction.d of class Destination
    destination_self_t* doublereaction_d_self = new_Destination();
    //***** Start initializing DoubleReaction.d
    // width of -2 indicates that it is not a multiport.
    doublereaction_d_self->__x__width = -2;
    // width of -2 indicates that it is not a multiport.
    doublereaction_d_self->__w__width = -2;
    static int doublereaction_d_initial_s = 2;
    doublereaction_d_self->s = doublereaction_d_initial_s;
    //***** End initializing DoubleReaction.d
    //***** End initializing DoubleReaction
    // Populate arrays of trigger pointers.
    doublereaction_self->bank_index = 0;
    doublereaction_c1_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    doublereaction_c1_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (doublereaction_c1_self->___reaction_0.num_outputs > 0) {
        doublereaction_c1_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * doublereaction_c1_self->___reaction_0.num_outputs);
        doublereaction_c1_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * doublereaction_c1_self->___reaction_0.num_outputs);
        doublereaction_c1_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * doublereaction_c1_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    doublereaction_c1_self->___reaction_0.output_produced[0]
    = &doublereaction_c1_self->__y.is_present
    ;
    // Reaction 0 of DoubleReaction.c1 does not depend on one maximal upstream reaction.
    doublereaction_c1_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of DoubleReaction.c1 triggers 1 downstream reactions through port DoubleReaction.c1.y.
    doublereaction_c1_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of DoubleReaction.c1, allocate an
    // array of trigger pointers for downstream reactions through port DoubleReaction.c1.y
    trigger_t** doublereaction_c1_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    doublereaction_c1_self->___reaction_0.triggers[0] = doublereaction_c1_0_0;
    // Point to destination port DoubleReaction.d.x's trigger struct.
    doublereaction_c1_0_0[0] = &doublereaction_d_self->___x;
    doublereaction_c1_self->__y.num_destinations
    = 1;
    doublereaction_c2_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    doublereaction_c2_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (doublereaction_c2_self->___reaction_0.num_outputs > 0) {
        doublereaction_c2_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * doublereaction_c2_self->___reaction_0.num_outputs);
        doublereaction_c2_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * doublereaction_c2_self->___reaction_0.num_outputs);
        doublereaction_c2_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * doublereaction_c2_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    doublereaction_c2_self->___reaction_0.output_produced[0]
    = &doublereaction_c2_self->__y.is_present
    ;
    // Reaction 0 of DoubleReaction.c2 does not depend on one maximal upstream reaction.
    doublereaction_c2_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of DoubleReaction.c2 triggers 1 downstream reactions through port DoubleReaction.c2.y.
    doublereaction_c2_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of DoubleReaction.c2, allocate an
    // array of trigger pointers for downstream reactions through port DoubleReaction.c2.y
    trigger_t** doublereaction_c2_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    doublereaction_c2_self->___reaction_0.triggers[0] = doublereaction_c2_0_0;
    // Point to destination port DoubleReaction.d.w's trigger struct.
    doublereaction_c2_0_0[0] = &doublereaction_d_self->___w;
    doublereaction_c2_self->__y.num_destinations
    = 1;
    doublereaction_d_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    doublereaction_d_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (doublereaction_d_self->___reaction_0.num_outputs > 0) {
        doublereaction_d_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * doublereaction_d_self->___reaction_0.num_outputs);
        doublereaction_d_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * doublereaction_d_self->___reaction_0.num_outputs);
        doublereaction_d_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * doublereaction_d_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of DoubleReaction.d does not depend on one maximal upstream reaction.
    doublereaction_d_self->___reaction_0.last_enabling_reaction = NULL;
    // doDeferredInitialize
    // Connect inputs and outputs for reactor DoubleReaction.
    // Connect DoubleReaction.c1.y to input port DoubleReaction.d.x
    doublereaction_d_self->__x = (destination_x_t*)&doublereaction_c1_self->__y;
    // Connect DoubleReaction.c2.y to input port DoubleReaction.d.w
    doublereaction_d_self->__w = (destination_w_t*)&doublereaction_c2_self->__y;
    // Connect inputs and outputs for reactor DoubleReaction.c1.
    // END Connect inputs and outputs for reactor DoubleReaction.c1.
    // Connect inputs and outputs for reactor DoubleReaction.c2.
    // END Connect inputs and outputs for reactor DoubleReaction.c2.
    // Connect inputs and outputs for reactor DoubleReaction.d.
    // END Connect inputs and outputs for reactor DoubleReaction.d.
    // END Connect inputs and outputs for reactor DoubleReaction.
    // Add port DoubleReaction.c1.y to array of is_present fields.
    __is_present_fields[0] = &doublereaction_c1_self->__y.is_present
    ;
    // Add port DoubleReaction.c2.y to array of is_present fields.
    __is_present_fields[1] = &doublereaction_c2_self->__y.is_present
    ;
    doublereaction_c1_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    doublereaction_c1_self->___reaction_0.index = 0x7fffffffffff0000LL;
    doublereaction_c2_self->___reaction_0.chain_id = 2;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    doublereaction_c2_self->___reaction_0.index = 0x7fffffffffff0000LL;
    doublereaction_d_self->___reaction_0.chain_id = 3;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    doublereaction_d_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
}
void __initialize_timers() {
    for (int i = 0; i < __timer_triggers_size; i++) {
        if (__timer_triggers[i] != NULL) {
            _lf_initialize_timer(__timer_triggers[i]);
        }
    }
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
