#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/GetTime.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class GetTime
typedef struct {
    int bank_index;
    #line 9 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    reaction_t ___reaction_0;
    #line 8 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    trigger_t ___t;
    #line 8 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    reaction_t* ___t_reactions[1];
} gettime_self_t;
void gettimereaction_function_0(void* instance_args) {
    gettime_self_t* self = (gettime_self_t*)instance_args;
    #line 10 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    instant_t logical = get_logical_time();
    printf("Logical time is %lld.\n", logical);
    
    interval_t elapsed = get_elapsed_logical_time();
    printf("Elapsed logical time is %lld.\n", elapsed);
    
    instant_t physical = get_physical_time();
    printf("Physical time is %lld.\n", physical);
    
    instant_t elapsed_physical = get_elapsed_physical_time();
    printf("Elapsed physical time is %lld.\n", elapsed_physical);
    
    printf("Time lag is %lld.\n", physical - logical);
        
}
gettime_self_t* new_GetTime() {
    gettime_self_t* self = (gettime_self_t*)calloc(1, sizeof(gettime_self_t));
    #line 9 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___reaction_0.number = 0;
    #line 9 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___reaction_0.function = gettimereaction_function_0;
    #line 9 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___reaction_0.self = self;
    #line 9 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 9 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 8 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___t.last = NULL;
    #line 8 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    #line 8 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___t_reactions[0] = &self->___reaction_0;
    #line 8 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___t.reactions = &self->___t_reactions[0];
    #line 8 "file:/lf-flexpret-scripts/tests/GetTime.lf"
    self->___t.number_of_reactions = 1;
    self->___t.is_timer = true;
    return self;
}
void delete_GetTime(gettime_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class GetTime

char* __default_argv[] = {"X", "-o", "2", "sec"};
void __set_default_command_line_options() {
    default_argc = 4;
    default_argv = __default_argv;
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
// Array of pointers to reactions to be scheduled in __trigger_startup_reactions().
reaction_t** __startup_reactions = NULL;
int __startup_reactions_size = 0;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // ************* Instance GetTime of class GetTime
    gettime_self_t* gettime_self = new_GetTime();
    //***** Start initializing GetTime
    gettime_self->___t.offset = 0;
    gettime_self->___t.period = SEC(1);
    __timer_triggers[0] = &gettime_self->___t;
    //***** End initializing GetTime
    // Populate arrays of trigger pointers.
    gettime_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    gettime_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (gettime_self->___reaction_0.num_outputs > 0) {
        gettime_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * gettime_self->___reaction_0.num_outputs);
        gettime_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * gettime_self->___reaction_0.num_outputs);
        gettime_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * gettime_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of GetTime does not depend on one maximal upstream reaction.
    gettime_self->___reaction_0.last_enabling_reaction = NULL;
    // doDeferredInitialize
    // Connect inputs and outputs for reactor GetTime.
    // END Connect inputs and outputs for reactor GetTime.
    
    gettime_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    gettime_self->___reaction_0.index = 0x7fffffffffff0000LL;
}
void __trigger_startup_reactions() {
    
}
void __initialize_timers() {
    for (int i = 0; i < __timer_triggers_size; i++) {
        if (__timer_triggers[i] != NULL) {
            _lf_initialize_timer(__timer_triggers[i]);
        }
    }
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
