#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/Hierarchy2.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Add
#line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} add_in1_t;
#line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} add_in2_t;
#line 25 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 25 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 25 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 25 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 25 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} add_out_t;
typedef struct {
    int bank_index;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    add_in1_t* __in1;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // width of -2 indicates that it is not a multiport.
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __in1__width;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Default input (in case it does not get connected)
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    add_in1_t __default__in1;
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    add_in2_t* __in2;
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // width of -2 indicates that it is not a multiport.
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __in2__width;
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Default input (in case it does not get connected)
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    add_in2_t __default__in2;
    #line 25 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    add_out_t __out;
    #line 25 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __out__width;
    #line 26 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t ___reaction_0;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    trigger_t ___in1;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t* ___in1_reactions[1];
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    trigger_t ___in2;
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t* ___in2_reactions[1];
} add_self_t;
void addreaction_function_0(void* instance_args) {
    add_self_t* self = (add_self_t*)instance_args;
    add_in1_t* in1 = self->__in1;
    int in1_width = self->__in1__width;
    add_in2_t* in2 = self->__in2;
    int in2_width = self->__in2__width;
    add_out_t* out = &self->__out;
    #line 27 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int result = 0;
    if (in1->is_present) result += in1->value;
    if (in2->is_present) result += in2->value;
    SET(out, result);
        
}
add_self_t* new_Add() {
    add_self_t* self = (add_self_t*)calloc(1, sizeof(add_self_t));
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Set input by default to an always absent default input.
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->__in1 = &self->__default__in1;
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Set input by default to an always absent default input.
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->__in2 = &self->__default__in2;
    #line 26 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.number = 0;
    #line 26 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.function = addreaction_function_0;
    #line 26 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.self = self;
    #line 26 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 26 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in1.last = NULL;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in1_reactions[0] = &self->___reaction_0;
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in1.reactions = &self->___in1_reactions[0];
    #line 23 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in1.number_of_reactions = 1;
    self->___in1.element_size = sizeof(int);
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in2.last = NULL;
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in2_reactions[0] = &self->___reaction_0;
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in2.reactions = &self->___in2_reactions[0];
    #line 24 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in2.number_of_reactions = 1;
    self->___in2.element_size = sizeof(int);
    return self;
}
void delete_Add(add_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Add

// =============== START reactor class Count
#line 14 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 14 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 14 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 14 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 14 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} count_out_t;
typedef struct {
    int bank_index;
    #line 16 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int i;
    #line 14 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    count_out_t __out;
    #line 14 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __out__width;
    #line 17 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t ___reaction_0;
    #line 15 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    trigger_t ___t;
    #line 15 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t* ___t_reactions[1];
} count_self_t;
void countreaction_function_0(void* instance_args) {
    count_self_t* self = (count_self_t*)instance_args;
    count_out_t* out = &self->__out;
    #line 18 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    (self->i)++;
    SET(out, self->i);
        
}
count_self_t* new_Count() {
    count_self_t* self = (count_self_t*)calloc(1, sizeof(count_self_t));
    #line 17 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.number = 0;
    #line 17 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.function = countreaction_function_0;
    #line 17 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.self = self;
    #line 17 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 17 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 15 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t.last = NULL;
    #line 15 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    #line 15 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t_reactions[0] = &self->___reaction_0;
    #line 15 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t.reactions = &self->___t_reactions[0];
    #line 15 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t.number_of_reactions = 1;
    self->___t.is_timer = true;
    return self;
}
void delete_Count(count_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Count

// =============== START reactor class Print
#line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} print_in_t;
typedef struct {
    int bank_index;
    #line 35 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int expected;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    print_in_t* __in;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // width of -2 indicates that it is not a multiport.
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __in__width;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Default input (in case it does not get connected)
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    print_in_t __default__in;
    #line 36 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t ___reaction_0;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    trigger_t ___in;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t* ___in_reactions[1];
} print_self_t;
void printreaction_function_0(void* instance_args) {
    print_self_t* self = (print_self_t*)instance_args;
    print_in_t* in = self->__in;
    int in_width = self->__in__width;
    #line 37 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    printf("Received: %d.\n", in->value);
    if (in->value != self->expected) {
        printf("Expected %d.\n", self->expected);
        exit(1);
    }
    self->expected++;
        
}
print_self_t* new_Print() {
    print_self_t* self = (print_self_t*)calloc(1, sizeof(print_self_t));
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Set input by default to an always absent default input.
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->__in = &self->__default__in;
    #line 36 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.number = 0;
    #line 36 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.function = printreaction_function_0;
    #line 36 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.self = self;
    #line 36 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 36 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in.last = NULL;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 34 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(int);
    return self;
}
void delete_Print(print_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Print

// =============== START reactor class Source
#line 7 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 7 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 7 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 7 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 7 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} source_out_t;
typedef struct {
    int bank_index;
    #line 7 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    source_out_t __out;
    #line 7 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __out__width;
    #line 9 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t ___reaction_0;
    #line 8 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    trigger_t ___t;
    #line 8 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    reaction_t* ___t_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args;
    source_out_t* out = &self->__out;
    #line 10 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    SET(out, 1);
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)calloc(1, sizeof(source_self_t));
    #line 9 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.number = 0;
    #line 9 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.function = sourcereaction_function_0;
    #line 9 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.self = self;
    #line 9 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 9 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 8 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t.last = NULL;
    #line 8 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    #line 8 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t_reactions[0] = &self->___reaction_0;
    #line 8 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t.reactions = &self->___t_reactions[0];
    #line 8 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___t.number_of_reactions = 1;
    self->___t.is_timer = true;
    return self;
}
void delete_Source(source_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Source

// =============== START reactor class AddCount
#line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} addcount_in_t;
#line 47 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
typedef struct {
#line 47 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int value;
#line 47 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    bool is_present;
#line 47 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int num_destinations;
#line 47 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
} addcount_out_t;
typedef struct {
    int bank_index;
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    addcount_in_t* __in;
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // width of -2 indicates that it is not a multiport.
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __in__width;
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Default input (in case it does not get connected)
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    addcount_in_t __default__in;
    #line 47 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    addcount_out_t __out;
    #line 47 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    int __out__width;
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    trigger_t ___in;
} addcount_self_t;
addcount_self_t* new_AddCount() {
    addcount_self_t* self = (addcount_self_t*)calloc(1, sizeof(addcount_self_t));
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    // Set input by default to an always absent default input.
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->__in = &self->__default__in;
    #line 46 "file:/lf-flexpret-scripts/tests/Hierarchy2.lf"
    self->___in.last = NULL;
    self->___in.element_size = sizeof(int);
    return self;
}
void delete_AddCount(addcount_self_t* self) {
    free(self);
}
// =============== END reactor class AddCount

// =============== START reactor class Hierarchy2
typedef struct {
    int bank_index;
} hierarchy2_self_t;
hierarchy2_self_t* new_Hierarchy2() {
    hierarchy2_self_t* self = (hierarchy2_self_t*)calloc(1, sizeof(hierarchy2_self_t));
    return self;
}
void delete_Hierarchy2(hierarchy2_self_t* self) {
    free(self);
}
// =============== END reactor class Hierarchy2

char* __default_argv[] = {"X", "-f", "true", "-o", "5", "sec"};
void __set_default_command_line_options() {
    default_argc = 6;
    default_argv = __default_argv;
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t* __timer_triggers[2];
int __timer_triggers_size = 2;
// Array of pointers to reactions to be scheduled in __trigger_startup_reactions().
reaction_t** __startup_reactions = NULL;
int __startup_reactions_size = 0;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 4;
    __is_present_fields = (bool**)malloc(4 * sizeof(bool*));
    // ************* Instance Hierarchy2 of class Hierarchy2
    hierarchy2_self_t* hierarchy2_self = new_Hierarchy2();
    //***** Start initializing Hierarchy2
    // ************* Instance Hierarchy2.source of class Source
    source_self_t* hierarchy2_source_self = new_Source();
    //***** Start initializing Hierarchy2.source
    // width of -2 indicates that it is not a multiport.
    hierarchy2_source_self->__out__width = -2;
    hierarchy2_source_self->___t.offset = 0;
    hierarchy2_source_self->___t.period = SEC(1);
    __timer_triggers[0] = &hierarchy2_source_self->___t;
    //***** End initializing Hierarchy2.source
    // ************* Instance Hierarchy2.addCount of class AddCount
    addcount_self_t* hierarchy2_addcount_self = new_AddCount();
    //***** Start initializing Hierarchy2.addCount
    // width of -2 indicates that it is not a multiport.
    hierarchy2_addcount_self->__out__width = -2;
    // width of -2 indicates that it is not a multiport.
    hierarchy2_addcount_self->__in__width = -2;
    // ************* Instance Hierarchy2.addCount.count of class Count
    count_self_t* hierarchy2_addcount_count_self = new_Count();
    //***** Start initializing Hierarchy2.addCount.count
    // width of -2 indicates that it is not a multiport.
    hierarchy2_addcount_count_self->__out__width = -2;
    static int hierarchy2_addcount_count_initial_i = 0;
    hierarchy2_addcount_count_self->i = hierarchy2_addcount_count_initial_i;
    hierarchy2_addcount_count_self->___t.offset = 0;
    hierarchy2_addcount_count_self->___t.period = SEC(1);
    __timer_triggers[1] = &hierarchy2_addcount_count_self->___t;
    //***** End initializing Hierarchy2.addCount.count
    // ************* Instance Hierarchy2.addCount.add of class Add
    add_self_t* hierarchy2_addcount_add_self = new_Add();
    //***** Start initializing Hierarchy2.addCount.add
    // width of -2 indicates that it is not a multiport.
    hierarchy2_addcount_add_self->__out__width = -2;
    // width of -2 indicates that it is not a multiport.
    hierarchy2_addcount_add_self->__in1__width = -2;
    // width of -2 indicates that it is not a multiport.
    hierarchy2_addcount_add_self->__in2__width = -2;
    //***** End initializing Hierarchy2.addCount.add
    //***** End initializing Hierarchy2.addCount
    // ************* Instance Hierarchy2.print of class Print
    print_self_t* hierarchy2_print_self = new_Print();
    //***** Start initializing Hierarchy2.print
    // width of -2 indicates that it is not a multiport.
    hierarchy2_print_self->__in__width = -2;
    static int hierarchy2_print_initial_expected = 2;
    hierarchy2_print_self->expected = hierarchy2_print_initial_expected;
    //***** End initializing Hierarchy2.print
    //***** End initializing Hierarchy2
    // Populate arrays of trigger pointers.
    hierarchy2_self->bank_index = 0;
    hierarchy2_source_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    hierarchy2_source_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (hierarchy2_source_self->___reaction_0.num_outputs > 0) {
        hierarchy2_source_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * hierarchy2_source_self->___reaction_0.num_outputs);
        hierarchy2_source_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * hierarchy2_source_self->___reaction_0.num_outputs);
        hierarchy2_source_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * hierarchy2_source_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    hierarchy2_source_self->___reaction_0.output_produced[0]
    = &hierarchy2_source_self->__out.is_present
    ;
    // Reaction 0 of Hierarchy2.source does not depend on one maximal upstream reaction.
    hierarchy2_source_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of Hierarchy2.source triggers 2 downstream reactions through port Hierarchy2.source.out.
    hierarchy2_source_self->___reaction_0.triggered_sizes[0] = 2;
    // For reaction 0 of Hierarchy2.source, allocate an
    // array of trigger pointers for downstream reactions through port Hierarchy2.source.out
    trigger_t** hierarchy2_source_0_0 = (trigger_t**)malloc(2 * sizeof(trigger_t*));
    hierarchy2_source_self->___reaction_0.triggers[0] = hierarchy2_source_0_0;
    // Destination port Hierarchy2.addCount.in itself has no reactions.
    hierarchy2_source_0_0[0] = NULL;
    // Point to destination port Hierarchy2.addCount.add.in1's trigger struct.
    hierarchy2_source_0_0[1] = &hierarchy2_addcount_add_self->___in1;
    hierarchy2_source_self->__out.num_destinations
    = 1;
    hierarchy2_addcount_self->bank_index = 0;
    hierarchy2_addcount_self->__out.num_destinations
    = 1;
    hierarchy2_addcount_count_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    hierarchy2_addcount_count_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (hierarchy2_addcount_count_self->___reaction_0.num_outputs > 0) {
        hierarchy2_addcount_count_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * hierarchy2_addcount_count_self->___reaction_0.num_outputs);
        hierarchy2_addcount_count_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * hierarchy2_addcount_count_self->___reaction_0.num_outputs);
        hierarchy2_addcount_count_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * hierarchy2_addcount_count_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    hierarchy2_addcount_count_self->___reaction_0.output_produced[0]
    = &hierarchy2_addcount_count_self->__out.is_present
    ;
    // Reaction 0 of Hierarchy2.addCount.count does not depend on one maximal upstream reaction.
    hierarchy2_addcount_count_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of Hierarchy2.addCount.count triggers 1 downstream reactions through port Hierarchy2.addCount.count.out.
    hierarchy2_addcount_count_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Hierarchy2.addCount.count, allocate an
    // array of trigger pointers for downstream reactions through port Hierarchy2.addCount.count.out
    trigger_t** hierarchy2_addcount_count_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    hierarchy2_addcount_count_self->___reaction_0.triggers[0] = hierarchy2_addcount_count_0_0;
    // Point to destination port Hierarchy2.addCount.add.in2's trigger struct.
    hierarchy2_addcount_count_0_0[0] = &hierarchy2_addcount_add_self->___in2;
    hierarchy2_addcount_count_self->__out.num_destinations
    = 1;
    hierarchy2_addcount_add_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    hierarchy2_addcount_add_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (hierarchy2_addcount_add_self->___reaction_0.num_outputs > 0) {
        hierarchy2_addcount_add_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * hierarchy2_addcount_add_self->___reaction_0.num_outputs);
        hierarchy2_addcount_add_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * hierarchy2_addcount_add_self->___reaction_0.num_outputs);
        hierarchy2_addcount_add_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * hierarchy2_addcount_add_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    hierarchy2_addcount_add_self->___reaction_0.output_produced[0]
    = &hierarchy2_addcount_add_self->__out.is_present
    ;
    // Reaction 0 of Hierarchy2.addCount.add does not depend on one maximal upstream reaction.
    hierarchy2_addcount_add_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of Hierarchy2.addCount.add triggers 2 downstream reactions through port Hierarchy2.addCount.add.out.
    hierarchy2_addcount_add_self->___reaction_0.triggered_sizes[0] = 2;
    // For reaction 0 of Hierarchy2.addCount.add, allocate an
    // array of trigger pointers for downstream reactions through port Hierarchy2.addCount.add.out
    trigger_t** hierarchy2_addcount_add_0_0 = (trigger_t**)malloc(2 * sizeof(trigger_t*));
    hierarchy2_addcount_add_self->___reaction_0.triggers[0] = hierarchy2_addcount_add_0_0;
    // Destination port Hierarchy2.addCount.out itself has no reactions.
    hierarchy2_addcount_add_0_0[0] = NULL;
    // Point to destination port Hierarchy2.print.in's trigger struct.
    hierarchy2_addcount_add_0_0[1] = &hierarchy2_print_self->___in;
    hierarchy2_addcount_add_self->__out.num_destinations
    = 1;
    hierarchy2_print_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    hierarchy2_print_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (hierarchy2_print_self->___reaction_0.num_outputs > 0) {
        hierarchy2_print_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * hierarchy2_print_self->___reaction_0.num_outputs);
        hierarchy2_print_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * hierarchy2_print_self->___reaction_0.num_outputs);
        hierarchy2_print_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * hierarchy2_print_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of Hierarchy2.print depends on one maximal upstream reaction.
    hierarchy2_print_self->___reaction_0.last_enabling_reaction = &(hierarchy2_addcount_add_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor Hierarchy2.
    // Connect Hierarchy2.source.out to input port Hierarchy2.addCount.in
    hierarchy2_addcount_self->__in = (addcount_in_t*)&hierarchy2_source_self->__out;
    // Connect Hierarchy2.addCount.out (eventual source is Hierarchy2.addCount.add.out) to input port Hierarchy2.print.in
    hierarchy2_print_self->__in = (print_in_t*)&hierarchy2_addcount_add_self->__out;
    // Connect inputs and outputs for reactor Hierarchy2.source.
    // END Connect inputs and outputs for reactor Hierarchy2.source.
    // Connect inputs and outputs for reactor Hierarchy2.addCount.
    // Connect Hierarchy2.addCount.in (eventual source is Hierarchy2.source.out) to input port Hierarchy2.addCount.add.in1
    hierarchy2_addcount_add_self->__in1 = (add_in1_t*)&hierarchy2_source_self->__out;
    // Connect Hierarchy2.addCount.count.out to input port Hierarchy2.addCount.add.in2
    hierarchy2_addcount_add_self->__in2 = (add_in2_t*)&hierarchy2_addcount_count_self->__out;
    // Connect inputs and outputs for reactor Hierarchy2.addCount.count.
    // END Connect inputs and outputs for reactor Hierarchy2.addCount.count.
    // Connect inputs and outputs for reactor Hierarchy2.addCount.add.
    // END Connect inputs and outputs for reactor Hierarchy2.addCount.add.
    // END Connect inputs and outputs for reactor Hierarchy2.addCount.
    // Connect inputs and outputs for reactor Hierarchy2.print.
    // END Connect inputs and outputs for reactor Hierarchy2.print.
    // END Connect inputs and outputs for reactor Hierarchy2.
    // Add port Hierarchy2.addCount.count.out to array of is_present fields.
    __is_present_fields[0] = &hierarchy2_addcount_count_self->__out.is_present
    ;
    // Add port Hierarchy2.addCount.add.out to array of is_present fields.
    __is_present_fields[1] = &hierarchy2_addcount_add_self->__out.is_present
    ;
    // Add port Hierarchy2.source.out to array of is_present fields.
    __is_present_fields[2] = &hierarchy2_source_self->__out.is_present
    ;
    // Add port Hierarchy2.addCount.out to array of is_present fields.
    __is_present_fields[3] = &hierarchy2_addcount_self->__out.is_present
    ;
    hierarchy2_source_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    hierarchy2_source_self->___reaction_0.index = 0x7fffffffffff0000LL;
    hierarchy2_addcount_count_self->___reaction_0.chain_id = 2;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    hierarchy2_addcount_count_self->___reaction_0.index = 0x7fffffffffff0000LL;
    hierarchy2_addcount_add_self->___reaction_0.chain_id = 3;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    hierarchy2_addcount_add_self->___reaction_0.index = 0x7fffffffffff0001LL;
    hierarchy2_print_self->___reaction_0.chain_id = 3;
    // index is the OR of level 2 and 
    // deadline 140737488355327 shifted left 16 bits.
    hierarchy2_print_self->___reaction_0.index = 0x7fffffffffff0002LL;
}
void __trigger_startup_reactions() {
    
}
void __initialize_timers() {
    for (int i = 0; i < __timer_triggers_size; i++) {
        if (__timer_triggers[i] != NULL) {
            _lf_initialize_timer(__timer_triggers[i]);
        }
    }
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
