#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/PeriodicDesugared.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Periodic
#line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
typedef struct {
#line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    trigger_t* trigger;
#line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    bool is_present;
#line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    bool has_value;
#line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    lf_token_t* token;
#line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
} periodic_init_t;
#line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
typedef struct {
#line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    trigger_t* trigger;
#line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    bool is_present;
#line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    bool has_value;
#line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    lf_token_t* token;
#line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
} periodic_recur_t;
typedef struct {
    int bank_index;
    #line 7 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    interval_t offset;
    #line 8 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    interval_t period;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    periodic_init_t __init;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    periodic_recur_t __recur;
    #line 12 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    reaction_t ___reaction_0;
    #line 21 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    reaction_t ___reaction_1;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    trigger_t ___init;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    reaction_t* ___init_reactions[1];
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    trigger_t ___recur;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    reaction_t* ___recur_reactions[1];
} periodic_self_t;
void periodicreaction_function_0(void* instance_args) {
    periodic_self_t* self = (periodic_self_t*)instance_args;
    periodic_init_t* init = &self->__init;
    periodic_recur_t* recur = &self->__recur;
    #line 13 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    if (self->offset == 0) {
        printf("Hello World!\n");
        schedule(recur, 0);        
    } else {
        schedule(init, 0);
    }
        
}
void periodicreaction_function_1(void* instance_args) {
    periodic_self_t* self = (periodic_self_t*)instance_args;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    // Expose the action struct as a local variable whose name matches the action name.
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    periodic_init_t* init = &self->__init;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    // Set the fields of the action struct to match the current trigger.
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    init->is_present = self->___init.is_present;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    init->has_value = ((self->___init.token) != NULL && (self->___init.token)->value != NULL);
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    init->token = (self->___init.token);
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    // Expose the action struct as a local variable whose name matches the action name.
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    periodic_recur_t* recur = &self->__recur;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    // Set the fields of the action struct to match the current trigger.
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    recur->is_present = self->___recur.is_present;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    recur->has_value = ((self->___recur.token) != NULL && (self->___recur.token)->value != NULL);
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    recur->token = (self->___recur.token);
    #line 22 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    printf("Hello World!\n");
    schedule(recur, 0);
        
}
periodic_self_t* new_Periodic() {
    periodic_self_t* self = (periodic_self_t*)calloc(1, sizeof(periodic_self_t));
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->__init.trigger = &self->___init;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->__recur.trigger = &self->___recur;
    #line 12 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_0.number = 0;
    #line 12 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_0.function = periodicreaction_function_0;
    #line 12 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_0.self = self;
    #line 12 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 12 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 21 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_1.number = 1;
    #line 21 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_1.function = periodicreaction_function_1;
    #line 21 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_1.self = self;
    #line 21 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_1.deadline_violation_handler = NULL;
    #line 21 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___reaction_1.tardy_handler = NULL;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___init.last = NULL;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___init_reactions[0] = &self->___reaction_1;
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___init.reactions = &self->___init_reactions[0];
    #line 9 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___init.number_of_reactions = 1;
    self->___init.is_physical = false;
    self->___init.element_size = 0;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___recur.last = NULL;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___recur_reactions[0] = &self->___reaction_1;
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___recur.reactions = &self->___recur_reactions[0];
    #line 10 "file:/lf-flexpret-scripts/tests/PeriodicDesugared.lf"
    self->___recur.number_of_reactions = 1;
    self->___recur.is_physical = false;
    self->___recur.element_size = 0;
    return self;
}
void delete_Periodic(periodic_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    if (self->___reaction_1.output_produced != NULL) {
        free(self->___reaction_1.output_produced);
    }
    if (self->___reaction_1.triggers != NULL) {
        free(self->___reaction_1.triggers);
    }
    if (self->___reaction_1.triggered_sizes != NULL) {
        free(self->___reaction_1.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    for(int i = 0; i < self->___reaction_1.num_outputs; i++) {
        free(self->___reaction_1.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Periodic

char* __default_argv[] = {"X", "-f", "true", "-o", "1", "sec"};
void __set_default_command_line_options() {
    default_argc = 6;
    default_argv = __default_argv;
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 2;
    __tokens_with_ref_count = (token_present_t*)malloc(2 * sizeof(token_present_t));
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 2;
    __is_present_fields = (bool**)malloc(2 * sizeof(bool*));
    // ************* Instance Periodic of class Periodic
    periodic_self_t* periodic_self = new_Periodic();
    //***** Start initializing Periodic
    periodic_self->offset = 0; 
    periodic_self->period = MSEC(500); 
    __startup_reactions[0] = &periodic_self->___reaction_0;
    periodic_self->___init.offset = 0;
    periodic_self->___init.period = -1;
    periodic_self->___recur.offset = MSEC(500);
    periodic_self->___recur.period = -1;
    periodic_self->___init.token = __create_token(0);
    periodic_self->___init.is_present = false;
    __tokens_with_ref_count[0].token
            = &periodic_self->___init.token;
    __tokens_with_ref_count[0].is_present
            = &periodic_self->___init.is_present;
    __tokens_with_ref_count[0].reset_is_present = true;
    periodic_self->___recur.token = __create_token(0);
    periodic_self->___recur.is_present = false;
    __tokens_with_ref_count[1].token
            = &periodic_self->___recur.token;
    __tokens_with_ref_count[1].is_present
            = &periodic_self->___recur.is_present;
    __tokens_with_ref_count[1].reset_is_present = true;
    //***** End initializing Periodic
    // Populate arrays of trigger pointers.
    periodic_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    periodic_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (periodic_self->___reaction_0.num_outputs > 0) {
        periodic_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * periodic_self->___reaction_0.num_outputs);
        periodic_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * periodic_self->___reaction_0.num_outputs);
        periodic_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * periodic_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Total number of outputs produced by the reaction.
    periodic_self->___reaction_1.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (periodic_self->___reaction_1.num_outputs > 0) {
        periodic_self->___reaction_1.output_produced = (bool**)malloc(sizeof(bool*) * periodic_self->___reaction_1.num_outputs);
        periodic_self->___reaction_1.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * periodic_self->___reaction_1.num_outputs);
        periodic_self->___reaction_1.triggered_sizes = (int*)malloc(sizeof(int) * periodic_self->___reaction_1.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of Periodic does not depend on one maximal upstream reaction.
    periodic_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 1 of Periodic depends on one maximal upstream reaction.
    periodic_self->___reaction_1.last_enabling_reaction = &(periodic_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor Periodic.
    // END Connect inputs and outputs for reactor Periodic.
    // Add action Periodic.init to array of is_present fields.
    __is_present_fields[0] 
            = &periodic_self->__init.is_present;
    // Add action Periodic.recur to array of is_present fields.
    __is_present_fields[1] 
            = &periodic_self->__recur.is_present;
    periodic_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    periodic_self->___reaction_0.index = 0x7fffffffffff0000LL;
    periodic_self->___reaction_1.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    periodic_self->___reaction_1.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
