#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/Stride.lf
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class Display
#line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
typedef struct {
#line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int value;
#line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    bool is_present;
#line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int num_destinations;
#line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
} display_x_t;
typedef struct {
    int bank_index;
    #line 18 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int expected;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    display_x_t* __x;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    // width of -2 indicates that it is not a multiport.
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int __x__width;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    // Default input (in case it does not get connected)
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    display_x_t __default__x;
    #line 19 "file:/lf-flexpret-scripts/tests/Stride.lf"
    reaction_t ___reaction_0;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    trigger_t ___x;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    reaction_t* ___x_reactions[1];
} display_self_t;
void displayreaction_function_0(void* instance_args) {
    display_self_t* self = (display_self_t*)instance_args;
    display_x_t* x = self->__x;
    int x_width = self->__x__width;
    #line 20 "file:/lf-flexpret-scripts/tests/Stride.lf"
    printf("Received: %d.\n", x->value);
    if (x->value != self->expected) {
        fprintf(stderr, "ERROR: Expected %d\n", self->expected);
    }
    self->expected += 2;
        
}
display_self_t* new_Display() {
    display_self_t* self = (display_self_t*)calloc(1, sizeof(display_self_t));
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    // Set input by default to an always absent default input.
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->__x = &self->__default__x;
    #line 19 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.number = 0;
    #line 19 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.function = displayreaction_function_0;
    #line 19 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.self = self;
    #line 19 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 19 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___x.last = NULL;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___x_reactions[0] = &self->___reaction_0;
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___x.reactions = &self->___x_reactions[0];
    #line 17 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___x.number_of_reactions = 1;
    self->___x.element_size = sizeof(int);
    return self;
}
void delete_Display(display_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Display

// =============== START reactor class Count
#line 9 "file:/lf-flexpret-scripts/tests/Stride.lf"
typedef struct {
#line 9 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int value;
#line 9 "file:/lf-flexpret-scripts/tests/Stride.lf"
    bool is_present;
#line 9 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int num_destinations;
#line 9 "file:/lf-flexpret-scripts/tests/Stride.lf"
} count_y_t;
typedef struct {
    int bank_index;
    #line 7 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int stride;
    #line 8 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int count;
    #line 9 "file:/lf-flexpret-scripts/tests/Stride.lf"
    count_y_t __y;
    #line 9 "file:/lf-flexpret-scripts/tests/Stride.lf"
    int __y__width;
    #line 11 "file:/lf-flexpret-scripts/tests/Stride.lf"
    reaction_t ___reaction_0;
    #line 10 "file:/lf-flexpret-scripts/tests/Stride.lf"
    trigger_t ___t;
    #line 10 "file:/lf-flexpret-scripts/tests/Stride.lf"
    reaction_t* ___t_reactions[1];
} count_self_t;
void countreaction_function_0(void* instance_args) {
    count_self_t* self = (count_self_t*)instance_args;
    count_y_t* y = &self->__y;
    #line 12 "file:/lf-flexpret-scripts/tests/Stride.lf"
    SET(y, self->count);
    self->count += self->stride;
        
}
count_self_t* new_Count() {
    count_self_t* self = (count_self_t*)calloc(1, sizeof(count_self_t));
    #line 11 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.number = 0;
    #line 11 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.function = countreaction_function_0;
    #line 11 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.self = self;
    #line 11 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 11 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 10 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___t.last = NULL;
    #line 10 "file:/lf-flexpret-scripts/tests/Stride.lf"
    #line 10 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___t_reactions[0] = &self->___reaction_0;
    #line 10 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___t.reactions = &self->___t_reactions[0];
    #line 10 "file:/lf-flexpret-scripts/tests/Stride.lf"
    self->___t.number_of_reactions = 1;
    self->___t.is_timer = true;
    return self;
}
void delete_Count(count_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Count

// =============== START reactor class Stride
typedef struct {
    int bank_index;
} stride_self_t;
stride_self_t* new_Stride() {
    stride_self_t* self = (stride_self_t*)calloc(1, sizeof(stride_self_t));
    return self;
}
void delete_Stride(stride_self_t* self) {
    free(self);
}
// =============== END reactor class Stride

char* __default_argv[] = {"X", "-f", "true", "-o", "2", "sec"};
void __set_default_command_line_options() {
    default_argc = 6;
    default_argv = __default_argv;
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t* __timer_triggers[1];
int __timer_triggers_size = 1;
// Array of pointers to reactions to be scheduled in __trigger_startup_reactions().
reaction_t** __startup_reactions = NULL;
int __startup_reactions_size = 0;
// Empty array of pointers to shutdown triggers.
reaction_t** __shutdown_reactions = NULL;
int __shutdown_reactions_size = 0;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 1;
    __is_present_fields = (bool**)malloc(1 * sizeof(bool*));
    // ************* Instance Stride of class Stride
    stride_self_t* stride_self = new_Stride();
    //***** Start initializing Stride
    // ************* Instance Stride.c of class Count
    count_self_t* stride_c_self = new_Count();
    //***** Start initializing Stride.c
    stride_c_self->stride = 2; 
    // width of -2 indicates that it is not a multiport.
    stride_c_self->__y__width = -2;
    static int stride_c_initial_count = 1;
    stride_c_self->count = stride_c_initial_count;
    stride_c_self->___t.offset = 0;
    stride_c_self->___t.period = MSEC(100);
    __timer_triggers[0] = &stride_c_self->___t;
    //***** End initializing Stride.c
    // ************* Instance Stride.d of class Display
    display_self_t* stride_d_self = new_Display();
    //***** Start initializing Stride.d
    // width of -2 indicates that it is not a multiport.
    stride_d_self->__x__width = -2;
    static int stride_d_initial_expected = 1;
    stride_d_self->expected = stride_d_initial_expected;
    //***** End initializing Stride.d
    //***** End initializing Stride
    // Populate arrays of trigger pointers.
    stride_self->bank_index = 0;
    stride_c_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    stride_c_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (stride_c_self->___reaction_0.num_outputs > 0) {
        stride_c_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * stride_c_self->___reaction_0.num_outputs);
        stride_c_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * stride_c_self->___reaction_0.num_outputs);
        stride_c_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * stride_c_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    stride_c_self->___reaction_0.output_produced[0]
    = &stride_c_self->__y.is_present
    ;
    // Reaction 0 of Stride.c does not depend on one maximal upstream reaction.
    stride_c_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of Stride.c triggers 1 downstream reactions through port Stride.c.y.
    stride_c_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of Stride.c, allocate an
    // array of trigger pointers for downstream reactions through port Stride.c.y
    trigger_t** stride_c_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    stride_c_self->___reaction_0.triggers[0] = stride_c_0_0;
    // Point to destination port Stride.d.x's trigger struct.
    stride_c_0_0[0] = &stride_d_self->___x;
    stride_c_self->__y.num_destinations
    = 1;
    stride_d_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    stride_d_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (stride_d_self->___reaction_0.num_outputs > 0) {
        stride_d_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * stride_d_self->___reaction_0.num_outputs);
        stride_d_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * stride_d_self->___reaction_0.num_outputs);
        stride_d_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * stride_d_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of Stride.d depends on one maximal upstream reaction.
    stride_d_self->___reaction_0.last_enabling_reaction = &(stride_c_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor Stride.
    // Connect Stride.c.y to input port Stride.d.x
    stride_d_self->__x = (display_x_t*)&stride_c_self->__y;
    // Connect inputs and outputs for reactor Stride.c.
    // END Connect inputs and outputs for reactor Stride.c.
    // Connect inputs and outputs for reactor Stride.d.
    // END Connect inputs and outputs for reactor Stride.d.
    // END Connect inputs and outputs for reactor Stride.
    // Add port Stride.c.y to array of is_present fields.
    __is_present_fields[0] = &stride_c_self->__y.is_present
    ;
    stride_c_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    stride_c_self->___reaction_0.index = 0x7fffffffffff0000LL;
    stride_d_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    stride_d_self->___reaction_0.index = 0x7fffffffffff0001LL;
}
void __trigger_startup_reactions() {
    
}
void __initialize_timers() {
    for (int i = 0; i < __timer_triggers_size; i++) {
        if (__timer_triggers[i] != NULL) {
            _lf_initialize_timer(__timer_triggers[i]);
        }
    }
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
