#include "ctarget.h"
// Code generated by the Lingua Franca compiler from file:
// /lf-flexpret-scripts/tests/StructScale.lf
#include "hello.h"
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
// =============== START reactor class TestInput
#line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
typedef struct {
#line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    hello_t* value;
#line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    bool is_present;
#line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int num_destinations;
#line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    lf_token_t* token;
#line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int length;
#line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
} testinput_in_t;
typedef struct {
    int bank_index;
    #line 24 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int expected;
    #line 27 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    bool invoked;
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    testinput_in_t* __in;
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    // width of -2 indicates that it is not a multiport.
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int __in__width;
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    // Default input (in case it does not get connected)
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    testinput_in_t __default__in;
    #line 29 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    reaction_t ___reaction_0;
    #line 37 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    reaction_t ___reaction_1;
    trigger_t ___shutdown;
    reaction_t* ___shutdown_reactions[1];
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    trigger_t ___in;
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    reaction_t* ___in_reactions[1];
} testinput_self_t;
void testinputreaction_function_0(void* instance_args) {
    testinput_self_t* self = (testinput_self_t*)instance_args;
    testinput_in_t* in = self->__in;
    if (in->is_present) {
        in->length = in->token->length;
        in->value = (hello_t*)in->token->value;
    } else {
        in->length = 0;
    }
    int in_width = self->__in__width;
    #line 30 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    printf("Received: name = %s, value = %d\n", in->value->name, in->value->value);
    if (in->value->value != self->expected) {
        printf("ERROR: Expected value to be %d.\n", self->expected);
        exit(1);
    }
    self->invoked = true;
        
}
void testinputreaction_function_1(void* instance_args) {
    testinput_self_t* self = (testinput_self_t*)instance_args;
    #line 38 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    if (self->invoked == false) {
        fprintf(stderr, "ERROR: No data received.\n");
        exit(2);
    }
        
}
testinput_self_t* new_TestInput() {
    testinput_self_t* self = (testinput_self_t*)calloc(1, sizeof(testinput_self_t));
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    // Set input by default to an always absent default input.
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->__in = &self->__default__in;
    #line 29 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.number = 0;
    #line 29 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.function = testinputreaction_function_0;
    #line 29 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.self = self;
    #line 29 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 29 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 37 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_1.number = 1;
    #line 37 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_1.function = testinputreaction_function_1;
    #line 37 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_1.self = self;
    #line 37 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_1.deadline_violation_handler = NULL;
    #line 37 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_1.tardy_handler = NULL;
    self->___shutdown_reactions[0] = &self->___reaction_1;
    self->___shutdown.last = NULL;
    self->___shutdown.reactions = &self->___shutdown_reactions[0];
    self->___shutdown.number_of_reactions = 1;
    self->___shutdown.is_timer = false;
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in.last = NULL;
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 26 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(hello_t);
    return self;
}
void delete_TestInput(testinput_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    if (self->___reaction_1.output_produced != NULL) {
        free(self->___reaction_1.output_produced);
    }
    if (self->___reaction_1.triggers != NULL) {
        free(self->___reaction_1.triggers);
    }
    if (self->___reaction_1.triggered_sizes != NULL) {
        free(self->___reaction_1.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    for(int i = 0; i < self->___reaction_1.num_outputs; i++) {
        free(self->___reaction_1.triggers[i]);
    }
    free(self);
}
// =============== END reactor class TestInput

// =============== START reactor class Print
#line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
typedef struct {
#line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    hello_t* value;
#line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    bool is_present;
#line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int num_destinations;
#line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    lf_token_t* token;
#line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int length;
#line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
} print_in_t;
#line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
typedef struct {
#line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    hello_t* value;
#line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    bool is_present;
#line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int num_destinations;
#line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    lf_token_t* token;
#line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int length;
#line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
} print_out_t;
typedef struct {
    int bank_index;
    #line 45 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int scale;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    print_in_t* __in;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    // width of -2 indicates that it is not a multiport.
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int __in__width;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    // Default input (in case it does not get connected)
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    print_in_t __default__in;
    #line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    print_out_t __out;
    #line 49 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int __out__width;
    #line 50 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    reaction_t ___reaction_0;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    trigger_t ___in;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    reaction_t* ___in_reactions[1];
} print_self_t;
void printreaction_function_0(void* instance_args) {
    print_self_t* self = (print_self_t*)instance_args;
    // Mutable input, so copy the input struct into a temporary variable.
    print_in_t __tmp_in = *(self->__in);
    print_in_t* in = &__tmp_in;
    if (in->is_present) {
        in->length = in->token->length;
        lf_token_t* _lf_input_token = in->token;
        in->token = writable_copy(_lf_input_token);
        if (in->token != _lf_input_token) {
            // A copy of the input token has been made.
            // This needs to be reference counted.
            in->token->ref_count = 1;
            // Repurpose the next_free pointer on the token to add to the list.
            in->token->next_free = _lf_more_tokens_with_ref_count;
            _lf_more_tokens_with_ref_count = in->token;
        }
        in->value = (hello_t*)in->token->value;
    } else {
        in->length = 0;
    }
    int in_width = self->__in__width;
    print_out_t* out = &self->__out;
    #line 51 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    in->value->value *= self->scale;
    SET_TOKEN(out, in->token);
        
}
print_self_t* new_Print() {
    print_self_t* self = (print_self_t*)calloc(1, sizeof(print_self_t));
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    // Set input by default to an always absent default input.
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->__in = &self->__default__in;
    #line 50 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.number = 0;
    #line 50 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.function = printreaction_function_0;
    #line 50 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.self = self;
    #line 50 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 50 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.tardy_handler = NULL;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in.last = NULL;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in_reactions[0] = &self->___reaction_0;
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in.reactions = &self->___in_reactions[0];
    #line 47 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___in.number_of_reactions = 1;
    self->___in.element_size = sizeof(hello_t);
    return self;
}
void delete_Print(print_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Print

// =============== START reactor class Source
#line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
typedef struct {
#line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    hello_t* value;
#line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    bool is_present;
#line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int num_destinations;
#line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    lf_token_t* token;
#line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int length;
#line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
} source_out_t;
typedef struct {
    int bank_index;
    #line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    source_out_t __out;
    #line 13 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    int __out__width;
    #line 14 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    reaction_t ___reaction_0;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args;
    source_out_t* out = &self->__out;
    #line 15 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    // Dynamically allocate an output struct.
    SET_NEW(out);
    // Above allocates a struct, which then must be populated.
    out->value->name = "Earth";
    out->value->value = 42;
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)calloc(1, sizeof(source_self_t));
    #line 14 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.number = 0;
    #line 14 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.function = sourcereaction_function_0;
    #line 14 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.self = self;
    #line 14 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.deadline_violation_handler = NULL;
    #line 14 "file:/lf-flexpret-scripts/tests/StructScale.lf"
    self->___reaction_0.tardy_handler = NULL;
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    return self;
}
void delete_Source(source_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    free(self);
}
// =============== END reactor class Source

// =============== START reactor class StructScale
typedef struct {
    int bank_index;
} structscale_self_t;
structscale_self_t* new_StructScale() {
    structscale_self_t* self = (structscale_self_t*)calloc(1, sizeof(structscale_self_t));
    return self;
}
void delete_StructScale(structscale_self_t* self) {
    free(self);
}
// =============== END reactor class StructScale

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t* __shutdown_reactions[1];
int __shutdown_reactions_size = 1;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    __tokens_with_ref_count_size = 2;
    __tokens_with_ref_count = (token_present_t*)malloc(2 * sizeof(token_present_t));
    // Create the array that will contain pointers to is_present fields to reset on each step.
    __is_present_fields_size = 2;
    __is_present_fields = (bool**)malloc(2 * sizeof(bool*));
    // ************* Instance StructScale of class StructScale
    structscale_self_t* structscale_self = new_StructScale();
    //***** Start initializing StructScale
    // ************* Instance StructScale.s of class Source
    source_self_t* structscale_s_self = new_Source();
    //***** Start initializing StructScale.s
    // width of -2 indicates that it is not a multiport.
    structscale_s_self->__out__width = -2;
    __startup_reactions[0] = &structscale_s_self->___reaction_0;
    //***** End initializing StructScale.s
    // ************* Instance StructScale.c of class Print
    print_self_t* structscale_c_self = new_Print();
    //***** Start initializing StructScale.c
    structscale_c_self->scale = 2; 
    // width of -2 indicates that it is not a multiport.
    structscale_c_self->__out__width = -2;
    // width of -2 indicates that it is not a multiport.
    structscale_c_self->__in__width = -2;
    //***** End initializing StructScale.c
    // ************* Instance StructScale.p of class TestInput
    testinput_self_t* structscale_p_self = new_TestInput();
    //***** Start initializing StructScale.p
    structscale_p_self->expected = 84; 
    __shutdown_reactions[0] = &structscale_p_self->___reaction_1;
    // width of -2 indicates that it is not a multiport.
    structscale_p_self->__in__width = -2;
    static bool structscale_p_initial_invoked = false;
    structscale_p_self->invoked = structscale_p_initial_invoked;
    //***** End initializing StructScale.p
    //***** End initializing StructScale
    // Populate arrays of trigger pointers.
    structscale_self->bank_index = 0;
    structscale_s_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    structscale_s_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (structscale_s_self->___reaction_0.num_outputs > 0) {
        structscale_s_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * structscale_s_self->___reaction_0.num_outputs);
        structscale_s_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * structscale_s_self->___reaction_0.num_outputs);
        structscale_s_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * structscale_s_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    structscale_s_self->___reaction_0.output_produced[0]
    = &structscale_s_self->__out.is_present
    ;
    // Reaction 0 of StructScale.s does not depend on one maximal upstream reaction.
    structscale_s_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 0 of StructScale.s triggers 1 downstream reactions through port StructScale.s.out.
    structscale_s_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of StructScale.s, allocate an
    // array of trigger pointers for downstream reactions through port StructScale.s.out
    trigger_t** structscale_s_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    structscale_s_self->___reaction_0.triggers[0] = structscale_s_0_0;
    // Point to destination port StructScale.c.in's trigger struct.
    structscale_s_0_0[0] = &structscale_c_self->___in;
    structscale_s_self->__out.num_destinations
    = 1;
    structscale_c_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    structscale_c_self->___reaction_0.num_outputs = 1;
    // Allocate arrays for triggering downstream reactions.
    if (structscale_c_self->___reaction_0.num_outputs > 0) {
        structscale_c_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * structscale_c_self->___reaction_0.num_outputs);
        structscale_c_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * structscale_c_self->___reaction_0.num_outputs);
        structscale_c_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * structscale_c_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    structscale_c_self->___reaction_0.output_produced[0]
    = &structscale_c_self->__out.is_present
    ;
    // Reaction 0 of StructScale.c depends on one maximal upstream reaction.
    structscale_c_self->___reaction_0.last_enabling_reaction = &(structscale_s_self->___reaction_0);
    // Reaction 0 of StructScale.c triggers 1 downstream reactions through port StructScale.c.out.
    structscale_c_self->___reaction_0.triggered_sizes[0] = 1;
    // For reaction 0 of StructScale.c, allocate an
    // array of trigger pointers for downstream reactions through port StructScale.c.out
    trigger_t** structscale_c_0_0 = (trigger_t**)malloc(1 * sizeof(trigger_t*));
    structscale_c_self->___reaction_0.triggers[0] = structscale_c_0_0;
    // Point to destination port StructScale.p.in's trigger struct.
    structscale_c_0_0[0] = &structscale_p_self->___in;
    structscale_c_self->__out.num_destinations
    = 1;
    structscale_p_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    structscale_p_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (structscale_p_self->___reaction_0.num_outputs > 0) {
        structscale_p_self->___reaction_0.output_produced = (bool**)malloc(sizeof(bool*) * structscale_p_self->___reaction_0.num_outputs);
        structscale_p_self->___reaction_0.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * structscale_p_self->___reaction_0.num_outputs);
        structscale_p_self->___reaction_0.triggered_sizes = (int*)malloc(sizeof(int) * structscale_p_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Total number of outputs produced by the reaction.
    structscale_p_self->___reaction_1.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (structscale_p_self->___reaction_1.num_outputs > 0) {
        structscale_p_self->___reaction_1.output_produced = (bool**)malloc(sizeof(bool*) * structscale_p_self->___reaction_1.num_outputs);
        structscale_p_self->___reaction_1.triggers = (trigger_t***)malloc(sizeof(trigger_t**) * structscale_p_self->___reaction_1.num_outputs);
        structscale_p_self->___reaction_1.triggered_sizes = (int*)malloc(sizeof(int) * structscale_p_self->___reaction_1.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of StructScale.p depends on one maximal upstream reaction.
    structscale_p_self->___reaction_0.last_enabling_reaction = &(structscale_c_self->___reaction_0);
    // Reaction 1 of StructScale.p depends on one maximal upstream reaction.
    structscale_p_self->___reaction_1.last_enabling_reaction = &(structscale_p_self->___reaction_0);
    // doDeferredInitialize
    structscale_s_self->__out.token = __create_token(sizeof(hello_t));
    structscale_c_self->__out.token = __create_token(sizeof(hello_t));
    // Connect inputs and outputs for reactor StructScale.
    // Connect StructScale.s.out to input port StructScale.c.in
    structscale_c_self->__in = (print_in_t*)&structscale_s_self->__out;
    // Connect StructScale.c.out to input port StructScale.p.in
    structscale_p_self->__in = (testinput_in_t*)&structscale_c_self->__out;
    // Connect inputs and outputs for reactor StructScale.s.
    // END Connect inputs and outputs for reactor StructScale.s.
    // Connect inputs and outputs for reactor StructScale.c.
    // END Connect inputs and outputs for reactor StructScale.c.
    // Connect inputs and outputs for reactor StructScale.p.
    // END Connect inputs and outputs for reactor StructScale.p.
    // END Connect inputs and outputs for reactor StructScale.
    __tokens_with_ref_count[0].token
            = &structscale_c_self->__in->token;
    __tokens_with_ref_count[0].is_present
            = &structscale_c_self->__in->is_present;
    __tokens_with_ref_count[0].reset_is_present = false;
    __tokens_with_ref_count[1].token
            = &structscale_p_self->__in->token;
    __tokens_with_ref_count[1].is_present
            = &structscale_p_self->__in->is_present;
    __tokens_with_ref_count[1].reset_is_present = false;
    // Add port StructScale.s.out to array of is_present fields.
    __is_present_fields[0] = &structscale_s_self->__out.is_present
    ;
    // Add port StructScale.c.out to array of is_present fields.
    __is_present_fields[1] = &structscale_c_self->__out.is_present
    ;
    structscale_s_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    structscale_s_self->___reaction_0.index = 0x7fffffffffff0000LL;
    structscale_c_self->___reaction_0.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    structscale_c_self->___reaction_0.index = 0x7fffffffffff0001LL;
    structscale_p_self->___reaction_0.chain_id = 1;
    // index is the OR of level 2 and 
    // deadline 140737488355327 shifted left 16 bits.
    structscale_p_self->___reaction_0.index = 0x7fffffffffff0002LL;
    structscale_p_self->___reaction_1.chain_id = 1;
    // index is the OR of level 3 and 
    // deadline 140737488355327 shifted left 16 bits.
    structscale_p_self->___reaction_1.index = 0x7fffffffffff0003LL;
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_time_complete(instant_t timestep, microstep_t microstep) {
}
tag_t next_event_tag(instant_t time, microstep_t microstep) {
    return (tag_t) {  .time = time, .microstep = microstep };
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void __termination() {stop_trace();}
